// Cross-validation tests for NSGA-II/III sorting, hypervolume, HSSP,
// box decomposition, and Pareto front identification.
// Python baseline generated by tests/generate_nsga_sorting_baseline.py.

use std::collections::HashMap;
use optuna_rs::multi_objective::{
    crowding_distance, dominates, fast_non_dominated_sort,
    hypervolume, hypervolume_2d, is_pareto_front,
    solve_hssp, get_non_dominated_box_bounds,
};
use optuna_rs::samplers::nsgaiii::{generate_reference_points, perpendicular_distance};
use optuna_rs::study::StudyDirection;
use optuna_rs::trial::{FrozenTrial, TrialState};

const TOL: f64 = 1e-10;
const TOL_RELAX: f64 = 1e-6;

fn load_baseline() -> serde_json::Value {
    let data = include_str!("nsga_sorting_baseline.json");
    serde_json::from_str(data).expect("Failed to parse nsga sorting baseline JSON")
}

fn get_f64(val: &serde_json::Value, key: &str) -> f64 {
    match &val[key] {
        serde_json::Value::Number(n) => n.as_f64().unwrap(),
        serde_json::Value::String(s) if s == "Infinity" => f64::INFINITY,
        serde_json::Value::String(s) if s == "-Infinity" => f64::NEG_INFINITY,
        serde_json::Value::String(s) if s == "NaN" => f64::NAN,
        v => panic!("Unexpected value for {key}: {v:?}"),
    }
}

fn get_f64_vec(val: &serde_json::Value, key: &str) -> Vec<f64> {
    val[key]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| match v {
            serde_json::Value::Number(n) => n.as_f64().unwrap(),
            serde_json::Value::String(s) if s == "Infinity" => f64::INFINITY,
            serde_json::Value::String(s) if s == "-Infinity" => f64::NEG_INFINITY,
            serde_json::Value::String(s) if s == "NaN" => f64::NAN,
            other => panic!("Unexpected value in {key}: {other:?}"),
        })
        .collect()
}

fn get_int_vec(val: &serde_json::Value, key: &str) -> Vec<i64> {
    val[key]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_i64().unwrap())
        .collect()
}

fn get_bool_vec(val: &serde_json::Value, key: &str) -> Vec<bool> {
    val[key]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| match v {
            serde_json::Value::Bool(b) => *b,
            serde_json::Value::Number(n) => n.as_i64().unwrap_or(0) != 0,
            other => panic!("Unexpected value in {key}: {other:?}"),
        })
        .collect()
}

fn assert_close(got: f64, expected: f64, tol: f64, label: &str) {
    if expected.is_infinite() {
        assert!(
            got.is_infinite() && got.signum() == expected.signum(),
            "{label}: expected {expected}, got {got}"
        );
    } else if expected.is_nan() {
        assert!(got.is_nan(), "{label}: expected NaN, got {got}");
    } else {
        let diff = (got - expected).abs();
        let denom = expected.abs().max(1.0);
        assert!(
            diff / denom < tol,
            "{label}: expected {expected}, got {got}, rel_err = {:.2e}",
            diff / denom
        );
    }
}

fn make_trial(number: i64, values: Vec<f64>) -> FrozenTrial {
    FrozenTrial::new(
        number,
        TrialState::Complete,
        None,
        Some(values),
        Some(chrono::Utc::now()),
        Some(chrono::Utc::now()),
        HashMap::new(),
        HashMap::new(),
        HashMap::new(),
        HashMap::new(),
        HashMap::new(),
        number,
    )
    .unwrap()
}

// ═══════════════════════════════════════════════════════════════════════════
//  1. Hypervolume 4D (WFG algorithm)
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_sort_hv_4d() {
    let b = load_baseline();
    let expected = get_f64(&b, "hv_4d");
    let points = vec![
        vec![1.0, 2.0, 3.0, 4.0],
        vec![2.0, 1.0, 4.0, 3.0],
        vec![3.0, 3.0, 1.0, 2.0],
        vec![4.0, 4.0, 2.0, 1.0],
    ];
    let reference = vec![6.0, 6.0, 6.0, 6.0];
    let hv = hypervolume(&points, &reference);
    assert_close(hv, expected, TOL, "hv_4d");
}

#[test]
fn cv_sort_hv_5d() {
    let b = load_baseline();
    let expected = get_f64(&b, "hv_5d");
    let points = vec![
        vec![1.0, 1.0, 1.0, 1.0, 1.0],
        vec![2.0, 2.0, 2.0, 2.0, 2.0],
    ];
    let reference = vec![5.0, 5.0, 5.0, 5.0, 5.0];
    let hv = hypervolume(&points, &reference);
    assert_close(hv, expected, TOL, "hv_5d");
}

#[test]
fn cv_sort_hv_4d_single() {
    let b = load_baseline();
    let expected = get_f64(&b, "hv_4d_single");
    let points = vec![vec![1.0, 2.0, 3.0, 4.0]];
    let reference = vec![10.0, 10.0, 10.0, 10.0];
    let hv = hypervolume(&points, &reference);
    assert_close(hv, expected, TOL, "hv_4d_single");
}

#[test]
fn cv_sort_hv_4d_mixed() {
    let b = load_baseline();
    let expected = get_f64(&b, "hv_4d_mixed");
    let points = vec![
        vec![1.0, 1.0, 1.0, 1.0],
        vec![2.0, 2.0, 2.0, 2.0],
        vec![3.0, 3.0, 3.0, 3.0],
    ];
    let reference = vec![5.0, 5.0, 5.0, 5.0];
    let hv = hypervolume(&points, &reference);
    assert_close(hv, expected, TOL, "hv_4d_mixed");
}

#[test]
fn cv_sort_hv_3d_large() {
    let b = load_baseline();
    let expected = get_f64(&b, "hv_3d_large");
    let points = vec![
        vec![1.0, 5.0, 3.0],
        vec![2.0, 3.0, 4.0],
        vec![3.0, 2.0, 2.0],
        vec![4.0, 1.0, 5.0],
        vec![5.0, 4.0, 1.0],
        vec![2.5, 2.5, 2.5],
    ];
    let reference = vec![8.0, 8.0, 8.0];
    let hv = hypervolume(&points, &reference);
    assert_close(hv, expected, TOL, "hv_3d_large");
}

// ═══════════════════════════════════════════════════════════════════════════
//  2. Hypervolume contributions (verify individual point contributions)
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_sort_hv_contributions_2d() {
    let b = load_baseline();
    let expected_total = get_f64(&b, "hv_total_2d");
    let expected_contribs = get_f64_vec(&b, "hv_contributions_2d");

    let points = vec![
        vec![1.0, 4.0],
        vec![2.0, 2.0],
        vec![4.0, 1.0],
    ];
    let reference = vec![6.0, 6.0];

    let hv_total = hypervolume(&points, &reference);
    assert_close(hv_total, expected_total, TOL, "hv_total_2d");

    // Compute individual contributions
    for i in 0..points.len() {
        let remaining: Vec<Vec<f64>> = points.iter()
            .enumerate()
            .filter(|(j, _)| *j != i)
            .map(|(_, p)| p.clone())
            .collect();
        let hv_without = hypervolume(&remaining, &reference);
        let contrib = hv_total - hv_without;
        assert_close(contrib, expected_contribs[i], TOL, &format!("hv_contrib[{i}]"));
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  3. HSSP (Hypervolume Subset Selection Problem)
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_sort_hssp_2d() {
    let b = load_baseline();
    let expected = get_int_vec(&b, "hssp_2d_indices");

    let points = vec![
        vec![1.0, 5.0],
        vec![2.0, 3.0],
        vec![3.0, 2.0],
        vec![4.0, 4.0],
        vec![5.0, 1.0],
    ];
    let indices: Vec<usize> = (0..points.len()).collect();
    let ref_point = vec![7.0, 7.0];

    let result = solve_hssp(&points, &indices, 3, &ref_point);
    let result_i64: Vec<i64> = result.iter().map(|&x| x as i64).collect();

    // HSSP 是贪心算法，选择的集合应该相同（顺序可能不同）
    let mut result_sorted = result_i64.clone();
    result_sorted.sort();
    let mut expected_sorted = expected.clone();
    expected_sorted.sort();
    assert_eq!(
        result_sorted, expected_sorted,
        "HSSP 2D: expected indices {:?}, got {:?}",
        expected, result_i64
    );
}

#[test]
fn cv_sort_hssp_3d() {
    let b = load_baseline();
    let expected = get_int_vec(&b, "hssp_3d_indices");

    let points = vec![
        vec![1.0, 3.0, 2.0],
        vec![2.0, 1.0, 3.0],
        vec![3.0, 2.0, 1.0],
        vec![1.5, 1.5, 1.5],
        vec![2.5, 2.5, 2.5],
    ];
    let indices: Vec<usize> = (0..points.len()).collect();
    let ref_point = vec![5.0, 5.0, 5.0];

    let result = solve_hssp(&points, &indices, 3, &ref_point);
    let result_i64: Vec<i64> = result.iter().map(|&x| x as i64).collect();

    let mut result_sorted = result_i64.clone();
    result_sorted.sort();
    let mut expected_sorted = expected.clone();
    expected_sorted.sort();
    assert_eq!(
        result_sorted, expected_sorted,
        "HSSP 3D: expected indices {:?}, got {:?}",
        expected, result_i64
    );
}

// ═══════════════════════════════════════════════════════════════════════════
//  4. Box decomposition
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_sort_box_decomp_2d() {
    let b = load_baseline();
    let expected_lower: Vec<Vec<f64>> = b["box_2d_lower"]
        .as_array().unwrap()
        .iter()
        .map(|row| row.as_array().unwrap().iter()
            .map(|v| match v {
                serde_json::Value::Number(n) => n.as_f64().unwrap(),
                serde_json::Value::String(s) if s == "-Infinity" => f64::NEG_INFINITY,
                serde_json::Value::String(s) if s == "Infinity" => f64::INFINITY,
                other => panic!("Unexpected: {other:?}"),
            }).collect()
        ).collect();
    let expected_upper: Vec<Vec<f64>> = b["box_2d_upper"]
        .as_array().unwrap()
        .iter()
        .map(|row| row.as_array().unwrap().iter()
            .map(|v| match v {
                serde_json::Value::Number(n) => n.as_f64().unwrap(),
                serde_json::Value::String(s) if s == "-Infinity" => f64::NEG_INFINITY,
                serde_json::Value::String(s) if s == "Infinity" => f64::INFINITY,
                other => panic!("Unexpected: {other:?}"),
            }).collect()
        ).collect();

    let points = vec![
        vec![1.0, 4.0],
        vec![2.0, 2.0],
        vec![4.0, 1.0],
    ];
    let ref_point = vec![6.0, 6.0];

    let (lower, upper) = get_non_dominated_box_bounds(&points, &ref_point);

    assert_eq!(lower.len(), expected_lower.len(), "box_2d lower count mismatch");
    assert_eq!(upper.len(), expected_upper.len(), "box_2d upper count mismatch");

    for (i, (got_l, exp_l)) in lower.iter().zip(expected_lower.iter()).enumerate() {
        for (j, (&g, &e)) in got_l.iter().zip(exp_l.iter()).enumerate() {
            assert_close(g, e, TOL, &format!("box_2d_lower[{i}][{j}]"));
        }
    }
    for (i, (got_u, exp_u)) in upper.iter().zip(expected_upper.iter()).enumerate() {
        for (j, (&g, &e)) in got_u.iter().zip(exp_u.iter()).enumerate() {
            assert_close(g, e, TOL, &format!("box_2d_upper[{i}][{j}]"));
        }
    }
}

#[test]
fn cv_sort_box_decomp_3d() {
    let b = load_baseline();
    let expected_lower: Vec<Vec<f64>> = b["box_3d_lower"]
        .as_array().unwrap()
        .iter()
        .map(|row| row.as_array().unwrap().iter()
            .map(|v| match v {
                serde_json::Value::Number(n) => n.as_f64().unwrap(),
                serde_json::Value::String(s) if s == "-Infinity" => f64::NEG_INFINITY,
                serde_json::Value::String(s) if s == "Infinity" => f64::INFINITY,
                other => panic!("Unexpected: {other:?}"),
            }).collect()
        ).collect();
    let expected_upper: Vec<Vec<f64>> = b["box_3d_upper"]
        .as_array().unwrap()
        .iter()
        .map(|row| row.as_array().unwrap().iter()
            .map(|v| match v {
                serde_json::Value::Number(n) => n.as_f64().unwrap(),
                serde_json::Value::String(s) if s == "-Infinity" => f64::NEG_INFINITY,
                serde_json::Value::String(s) if s == "Infinity" => f64::INFINITY,
                other => panic!("Unexpected: {other:?}"),
            }).collect()
        ).collect();

    let points = vec![
        vec![1.0, 3.0, 2.0],
        vec![2.0, 1.0, 3.0],
        vec![3.0, 2.0, 1.0],
    ];
    let ref_point = vec![5.0, 5.0, 5.0];

    let (lower, upper) = get_non_dominated_box_bounds(&points, &ref_point);

    assert_eq!(lower.len(), expected_lower.len(), "box_3d lower count mismatch");
    assert_eq!(upper.len(), expected_upper.len(), "box_3d upper count mismatch");

    for (i, (got_l, exp_l)) in lower.iter().zip(expected_lower.iter()).enumerate() {
        for (j, (&g, &e)) in got_l.iter().zip(exp_l.iter()).enumerate() {
            assert_close(g, e, TOL, &format!("box_3d_lower[{i}][{j}]"));
        }
    }
    for (i, (got_u, exp_u)) in upper.iter().zip(expected_upper.iter()).enumerate() {
        for (j, (&g, &e)) in got_u.iter().zip(exp_u.iter()).enumerate() {
            assert_close(g, e, TOL, &format!("box_3d_upper[{i}][{j}]"));
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  5. Non-dominated sorting: mixed directions
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_sort_nds_mixed_direction() {
    let b = load_baseline();
    let expected = get_int_vec(&b, "nds_ranks_mixed_dir");

    // obj0: Minimize, obj1: Maximize
    // Original values (NOT negated — Rust handles direction internally)
    let trials: Vec<FrozenTrial> = vec![
        make_trial(0, vec![1.0, 5.0]),
        make_trial(1, vec![2.0, 4.0]),
        make_trial(2, vec![3.0, 3.0]),
        make_trial(3, vec![4.0, 2.0]),
        make_trial(4, vec![5.0, 1.0]),
        make_trial(5, vec![2.5, 2.5]),
        make_trial(6, vec![1.5, 4.5]),
        make_trial(7, vec![4.5, 1.5]),
        make_trial(8, vec![3.0, 3.0]),
        make_trial(9, vec![6.0, 6.0]),
    ];
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Maximize];
    let fronts = fast_non_dominated_sort(&trial_refs, &dirs);

    let mut ranks = vec![0i64; trials.len()];
    for (rank, front) in fronts.iter().enumerate() {
        for &idx in front {
            ranks[idx] = rank as i64;
        }
    }
    assert_eq!(ranks, expected, "nds_ranks_mixed_dir mismatch");
}

#[test]
fn cv_sort_nds_3obj_10() {
    let b = load_baseline();
    let expected = get_int_vec(&b, "nds_ranks_3obj_10");

    let trials: Vec<FrozenTrial> = vec![
        make_trial(0, vec![1.0, 5.0, 3.0]),
        make_trial(1, vec![2.0, 1.0, 5.0]),
        make_trial(2, vec![5.0, 2.0, 1.0]),
        make_trial(3, vec![3.0, 3.0, 3.0]),
        make_trial(4, vec![4.0, 4.0, 4.0]),
        make_trial(5, vec![1.5, 4.0, 2.0]),
        make_trial(6, vec![2.5, 2.5, 2.5]),
        make_trial(7, vec![6.0, 6.0, 6.0]),
        make_trial(8, vec![1.0, 1.0, 6.0]),
        make_trial(9, vec![3.5, 1.5, 1.5]),
    ];
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let dirs = vec![
        StudyDirection::Minimize,
        StudyDirection::Minimize,
        StudyDirection::Minimize,
    ];
    let fronts = fast_non_dominated_sort(&trial_refs, &dirs);

    let mut ranks = vec![0i64; trials.len()];
    for (rank, front) in fronts.iter().enumerate() {
        for &idx in front {
            ranks[idx] = rank as i64;
        }
    }
    assert_eq!(ranks, expected, "nds_ranks_3obj_10 mismatch");
}

// ═══════════════════════════════════════════════════════════════════════════
//  6. Large NDS (20 trials, random values)
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_sort_nds_large_20() {
    let b = load_baseline();
    let expected_ranks = get_int_vec(&b, "large_nds_ranks");
    let values: Vec<Vec<f64>> = b["large_nds_values"]
        .as_array().unwrap()
        .iter()
        .map(|row| row.as_array().unwrap().iter()
            .map(|v| v.as_f64().unwrap()).collect())
        .collect();

    let trials: Vec<FrozenTrial> = values.iter().enumerate()
        .map(|(i, v)| make_trial(i as i64, v.clone()))
        .collect();
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];
    let fronts = fast_non_dominated_sort(&trial_refs, &dirs);

    let mut ranks = vec![0i64; trials.len()];
    for (rank, front) in fronts.iter().enumerate() {
        for &idx in front {
            ranks[idx] = rank as i64;
        }
    }
    assert_eq!(ranks, expected_ranks, "large_nds_ranks mismatch");
}

// ═══════════════════════════════════════════════════════════════════════════
//  7. Pareto front identification
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_sort_pareto_front_2d() {
    let b = load_baseline();
    let expected = get_bool_vec(&b, "pareto_front_mask");

    let trials: Vec<FrozenTrial> = vec![
        make_trial(0, vec![1.0, 4.0]),
        make_trial(1, vec![2.0, 2.0]),
        make_trial(2, vec![4.0, 1.0]),
        make_trial(3, vec![3.0, 3.0]),
        make_trial(4, vec![5.0, 5.0]),
        make_trial(5, vec![1.5, 3.0]),
    ];
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];
    let result = is_pareto_front(&trial_refs, &dirs);

    assert_eq!(result, expected, "pareto_front_mask mismatch");
}

#[test]
fn cv_sort_pareto_front_3d() {
    let b = load_baseline();
    let expected = get_bool_vec(&b, "pareto_front_3d_mask");

    let trials: Vec<FrozenTrial> = vec![
        make_trial(0, vec![1.0, 3.0, 2.0]),
        make_trial(1, vec![2.0, 1.0, 3.0]),
        make_trial(2, vec![3.0, 2.0, 1.0]),
        make_trial(3, vec![2.0, 2.0, 2.0]),
        make_trial(4, vec![4.0, 4.0, 4.0]),
    ];
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let dirs = vec![
        StudyDirection::Minimize,
        StudyDirection::Minimize,
        StudyDirection::Minimize,
    ];
    let result = is_pareto_front(&trial_refs, &dirs);

    assert_eq!(result, expected, "pareto_front_3d_mask mismatch");
}

// ═══════════════════════════════════════════════════════════════════════════
//  8. Perpendicular distance (NSGA-III)
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_sort_perpendicular_distance() {
    let b = load_baseline();
    let expected = get_f64_vec(&b, "perpendicular_distances");

    let cases: Vec<(Vec<f64>, Vec<f64>)> = vec![
        (vec![1.0, 0.0], vec![1.0, 0.0]),
        (vec![1.0, 1.0], vec![1.0, 0.0]),
        (vec![0.5, 0.5], vec![1.0, 1.0]),
        (vec![1.0, 2.0, 3.0], vec![1.0, 1.0, 1.0]),
        (vec![3.0, 0.0, 0.0], vec![1.0, 0.0, 0.0]),
        (vec![1.0, 1.0, 1.0], vec![0.0, 0.0, 1.0]),
    ];

    for (i, ((pt, dir), &exp)) in cases.iter().zip(expected.iter()).enumerate() {
        let got = perpendicular_distance(pt, dir);
        assert_close(got, exp, TOL, &format!("perp_dist[{i}]"));
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  9. Das-Dennis reference points
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_sort_das_dennis_counts() {
    let b = load_baseline();
    let expected_counts = get_int_vec(&b, "dd_counts");

    let cases = [(2, 4), (3, 3), (4, 3), (5, 2)];
    for (i, &(n_obj, div)) in cases.iter().enumerate() {
        let pts = generate_reference_points(n_obj, div);
        assert_eq!(
            pts.len() as i64, expected_counts[i],
            "Das-Dennis({n_obj}, {div}) count mismatch"
        );
    }
}

#[test]
fn cv_sort_das_dennis_points_2d_4div() {
    let b = load_baseline();
    let expected: Vec<Vec<f64>> = b["dd_points"]["dd_2d_4div"]
        .as_array().unwrap()
        .iter()
        .map(|row| row.as_array().unwrap().iter()
            .map(|v| v.as_f64().unwrap()).collect::<Vec<f64>>())
        .collect();

    let mut got = generate_reference_points(2, 4);
    got.sort_by(|a: &Vec<f64>, b: &Vec<f64>| {
        for i in 0..a.len() {
            match a[i].partial_cmp(&b[i]) {
                Some(std::cmp::Ordering::Equal) => continue,
                Some(ord) => return ord,
                None => return std::cmp::Ordering::Equal,
            }
        }
        std::cmp::Ordering::Equal
    });

    assert_eq!(got.len(), expected.len(), "dd_2d_4div point count");
    for (i, (g, e)) in got.iter().zip(expected.iter()).enumerate() {
        for (j, (gv, ev)) in g.iter().zip(e.iter()).enumerate() {
            assert_close(*gv, *ev, TOL, &format!("dd_2d_4div[{i}][{j}]"));
        }
    }
}

#[test]
fn cv_sort_das_dennis_points_3d_3div() {
    let b = load_baseline();
    let expected: Vec<Vec<f64>> = b["dd_points"]["dd_3d_3div"]
        .as_array().unwrap()
        .iter()
        .map(|row| row.as_array().unwrap().iter()
            .map(|v| v.as_f64().unwrap()).collect::<Vec<f64>>())
        .collect();

    let mut got = generate_reference_points(3, 3);
    got.sort_by(|a: &Vec<f64>, b: &Vec<f64>| {
        for i in 0..a.len() {
            match a[i].partial_cmp(&b[i]) {
                Some(std::cmp::Ordering::Equal) => continue,
                Some(ord) => return ord,
                None => return std::cmp::Ordering::Equal,
            }
        }
        std::cmp::Ordering::Equal
    });

    assert_eq!(got.len(), expected.len(), "dd_3d_3div point count");
    for (i, (g, e)) in got.iter().zip(expected.iter()).enumerate() {
        for (j, (gv, ev)) in g.iter().zip(e.iter()).enumerate() {
            assert_close(*gv, *ev, TOL, &format!("dd_3d_3div[{i}][{j}]"));
        }
    }
}

#[test]
fn cv_sort_das_dennis_points_4d_3div() {
    let b = load_baseline();
    let expected: Vec<Vec<f64>> = b["dd_points"]["dd_4d_3div"]
        .as_array().unwrap()
        .iter()
        .map(|row| row.as_array().unwrap().iter()
            .map(|v| v.as_f64().unwrap()).collect::<Vec<f64>>())
        .collect();

    let mut got = generate_reference_points(4, 3);
    got.sort_by(|a: &Vec<f64>, b: &Vec<f64>| {
        for i in 0..a.len() {
            match a[i].partial_cmp(&b[i]) {
                Some(std::cmp::Ordering::Equal) => continue,
                Some(ord) => return ord,
                None => return std::cmp::Ordering::Equal,
            }
        }
        std::cmp::Ordering::Equal
    });

    assert_eq!(got.len(), expected.len(), "dd_4d_3div point count");
    for (i, (g, e)) in got.iter().zip(expected.iter()).enumerate() {
        for (j, (gv, ev)) in g.iter().zip(e.iter()).enumerate() {
            assert_close(*gv, *ev, TOL, &format!("dd_4d_3div[{i}][{j}]"));
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// 10. Das-Dennis structural properties
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_sort_das_dennis_sum_to_one() {
    for (n_obj, div) in [(2, 4), (3, 3), (4, 3), (5, 2)] {
        let pts = generate_reference_points(n_obj, div);
        for (i, pt) in pts.iter().enumerate() {
            let sum: f64 = pt.iter().copied().sum();
            assert_close(sum, 1.0, TOL, &format!("dd({n_obj},{div}) pt[{i}] sum"));
        }
    }
}

#[test]
fn cv_sort_das_dennis_non_negative() {
    for (n_obj, div) in [(2, 4), (3, 3), (4, 3), (5, 2)] {
        let pts = generate_reference_points(n_obj, div);
        for (i, pt) in pts.iter().enumerate() {
            for (j, v) in pt.iter().enumerate() {
                assert!(*v >= 0.0, "dd({n_obj},{div}) pt[{i}][{j}] = {v} < 0");
            }
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// 11. Dominance properties
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_sort_dominates_nan_handling() {
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];
    // NaN in partial_cmp returns None → treated as "not worse" (skip),
    // so [NaN, 1.0] vs [2.0, 2.0]: dim0 NaN→skip, dim1 1<2→dominated_in_any=true → true!
    // This matches Rust's partial_cmp semantics. Python avoids NaN in values.
    // Key property: identical NaN values should NOT dominate.
    assert!(!dominates(&[f64::NAN, f64::NAN], &[f64::NAN, f64::NAN], &dirs));
    // Two NaN dimensions cannot establish dominated_in_any
    assert!(!dominates(&[f64::NAN, f64::NAN], &[1.0, 1.0], &dirs));
    // Self-dominance is always false
    assert!(!dominates(&[1.0, 1.0], &[1.0, 1.0], &dirs));
}

#[test]
fn cv_sort_crowding_distance_preserves_order() {
    // Crowding distance should be independent of input order
    let trials1: Vec<FrozenTrial> = vec![
        make_trial(0, vec![1.0, 5.0]),
        make_trial(1, vec![3.0, 3.0]),
        make_trial(2, vec![5.0, 1.0]),
    ];
    let trials2: Vec<FrozenTrial> = vec![
        make_trial(0, vec![5.0, 1.0]),
        make_trial(1, vec![1.0, 5.0]),
        make_trial(2, vec![3.0, 3.0]),
    ];

    let refs1: Vec<&FrozenTrial> = trials1.iter().collect();
    let refs2: Vec<&FrozenTrial> = trials2.iter().collect();
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];

    let cd1 = crowding_distance(&refs1, &dirs);
    let cd2 = crowding_distance(&refs2, &dirs);

    // cd1[0] should equal cd2[1] (both are [1, 5])
    assert_close(cd1[0], cd2[1], TOL, "cd order [1,5]");
    // cd1[1] should equal cd2[2] (both are [3, 3])
    assert_close(cd1[1], cd2[2], TOL, "cd order [3,3]");
    // cd1[2] should equal cd2[0] (both are [5, 1])
    assert_close(cd1[2], cd2[0], TOL, "cd order [5,1]");
}

// ═══════════════════════════════════════════════════════════════════════════
// 12. End-to-end: NDS → Crowding distance → Elite selection
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_sort_nds_then_crowding() {
    // Verify the pipeline: NDS assigns ranks, then crowding distance
    // breaks ties within the same front
    let trials: Vec<FrozenTrial> = vec![
        make_trial(0, vec![1.0, 4.0]),   // front 0
        make_trial(1, vec![2.0, 2.0]),   // front 0
        make_trial(2, vec![4.0, 1.0]),   // front 0
        make_trial(3, vec![3.0, 3.0]),   // front 1
        make_trial(4, vec![5.0, 5.0]),   // front 2
    ];
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];

    // Step 1: NDS
    let fronts = fast_non_dominated_sort(&trial_refs, &dirs);
    assert_eq!(fronts.len(), 3, "Expected 3 fronts");
    assert_eq!(fronts[0].len(), 3, "Front 0 should have 3 trials");
    assert_eq!(fronts[1].len(), 1, "Front 1 should have 1 trial");
    assert_eq!(fronts[2].len(), 1, "Front 2 should have 1 trial");

    // Step 2: Crowding distance on front 0
    let front0_trials: Vec<&FrozenTrial> = fronts[0].iter().map(|&i| &trials[i]).collect();
    let cd = crowding_distance(&front0_trials, &dirs);

    // Boundary solutions should have infinite crowding distance
    // The sorted order for obj0 is: trial0(1.0), trial1(2.0), trial2(4.0)
    // Boundary = first and last in each dimension → trial0 and trial2
    // With sentinel padding, boundaries always get contributions from inf gaps
    // In a 3-point front, the middle point gets finite CD
    assert!(cd.iter().any(|&c| c.is_finite()), "At least one non-boundary in front 0");
}

// ═══════════════════════════════════════════════════════════════════════════
// 13. Hypervolume edge cases
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_sort_hv_empty() {
    let points: Vec<Vec<f64>> = vec![];
    let reference = vec![5.0, 5.0];
    assert_eq!(hypervolume(&points, &reference), 0.0, "HV of empty set");
}

#[test]
fn cv_sort_hv_dominated_point() {
    // Point beyond reference should contribute nothing
    let points = vec![
        vec![1.0, 1.0],
        vec![10.0, 10.0],  // beyond reference
    ];
    let reference = vec![5.0, 5.0];
    let hv = hypervolume(&points, &reference);
    // Should equal HV of just the first point
    let hv_single = hypervolume(&vec![vec![1.0, 1.0]], &reference);
    assert_close(hv, hv_single, TOL, "HV dominated point");
}

#[test]
fn cv_sort_hv_2d_via_generic() {
    // Verify generic hypervolume matches hypervolume_2d for 2D case
    let points = vec![
        vec![1.0, 4.0],
        vec![2.0, 2.0],
        vec![4.0, 1.0],
    ];
    let reference = vec![6.0, 6.0];
    let hv_generic = hypervolume(&points, &reference);

    let pts_2d: Vec<[f64; 2]> = points.iter().map(|p| [p[0], p[1]]).collect();
    let hv_2d = hypervolume_2d(&pts_2d, [6.0, 6.0]);

    assert_close(hv_generic, hv_2d, TOL, "HV 2D generic vs specialized");
}
