// ═══════════════════════════════════════════════════════════════════════════════
// Deep cross-validation of NSGA-II non-dominated sorting against Python Optuna.
//
// Baseline: tests/nsga_deep_baseline.json (generated by generate_nsga_deep_baseline.py)
// Covers:
//  1. dominates() — all direction combos, inf, equal, trade-off
//  2. fast_non_dominated_sort() — rank assignment with duplicates, 3+ fronts, 
//     single obj, mixed direction, NaN objectives
//  3. crowding_distance() — Python-exact normalization, inf padding, sort order
//  4. is_pareto_front() — front membership
//  5. Large 10-trial 3-obj problem — full pipeline
// ═══════════════════════════════════════════════════════════════════════════════

use std::collections::HashMap;
use optuna_rs::multi_objective::{
    crowding_distance, dominates, fast_non_dominated_sort, is_pareto_front,
};
use optuna_rs::study::StudyDirection;
use optuna_rs::trial::{FrozenTrial, TrialState};

const TOL: f64 = 1e-9;

fn load() -> serde_json::Value {
    let data = include_str!("nsga_deep_baseline.json");
    serde_json::from_str(data).expect("parse nsga_deep_baseline.json")
}

fn jf64(v: &serde_json::Value) -> f64 {
    match v {
        serde_json::Value::Number(n) => n.as_f64().unwrap(),
        serde_json::Value::String(s) if s == "Infinity" => f64::INFINITY,
        serde_json::Value::String(s) if s == "-Infinity" => f64::NEG_INFINITY,
        serde_json::Value::String(s) if s == "NaN" => f64::NAN,
        _ => panic!("unexpected json value: {v:?}"),
    }
}

fn jf64_vec(arr: &serde_json::Value) -> Vec<f64> {
    arr.as_array().unwrap().iter().map(jf64).collect()
}

fn ji64_vec(arr: &serde_json::Value) -> Vec<i64> {
    arr.as_array().unwrap().iter().map(|v| v.as_i64().unwrap()).collect()
}

fn assert_close(got: f64, exp: f64, tol: f64, label: &str) {
    if exp.is_infinite() {
        assert!(
            got.is_infinite() && got.signum() == exp.signum(),
            "{label}: expected {exp}, got {got}"
        );
    } else if exp.is_nan() {
        assert!(got.is_nan(), "{label}: expected NaN, got {got}");
    } else {
        let diff = (got - exp).abs();
        let denom = exp.abs().max(1.0);
        assert!(
            diff / denom < tol,
            "{label}: expected {exp}, got {got}, rel_err={:.2e}",
            diff / denom
        );
    }
}

fn make_trial(number: i64, values: Vec<f64>) -> FrozenTrial {
    FrozenTrial::new(
        number,
        TrialState::Complete,
        None,
        Some(values),
        Some(chrono::Utc::now()),
        Some(chrono::Utc::now()),
        HashMap::new(),
        HashMap::new(),
        HashMap::new(),
        HashMap::new(),
        HashMap::new(),
        number,
    )
    .unwrap()
}

/// Convert fronts (Vec<Vec<usize>>) to per-trial rank array
fn fronts_to_ranks(fronts: &[Vec<usize>], n: usize) -> Vec<i64> {
    let mut ranks = vec![-1i64; n];
    for (rank, front) in fronts.iter().enumerate() {
        for &idx in front {
            ranks[idx] = rank as i64;
        }
    }
    ranks
}

// ═══════════════════════════════════════════════════════════════════════════
//  1. dominates() — 1D cases from Python test_dominates_1d_not_equal
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn deep_cv_dominates_1d_not_equal() {
    let b = load();
    let cases = b["dom_1d_not_equal"].as_array().unwrap();
    for (i, case) in cases.iter().enumerate() {
        let v1 = jf64(&case["v1"]);
        let v2 = jf64(&case["v2"]);
        let py_dom_min = case["dom_min"].as_bool().unwrap();
        let py_dom_max = case["dom_max"].as_bool().unwrap();

        let rs_dom_min = dominates(&[v1], &[v2], &[StudyDirection::Minimize]);
        let rs_dom_max = dominates(&[v1], &[v2], &[StudyDirection::Maximize]);

        assert_eq!(
            rs_dom_min, py_dom_min,
            "dom_1d_not_equal[{i}] minimize: v1={v1}, v2={v2}"
        );
        assert_eq!(
            rs_dom_max, py_dom_max,
            "dom_1d_not_equal[{i}] maximize: v1={v1}, v2={v2}"
        );
    }
}

#[test]
fn deep_cv_dominates_1d_equal() {
    let b = load();
    let cases = b["dom_1d_equal"].as_array().unwrap();
    for (i, case) in cases.iter().enumerate() {
        let v = jf64(&case["v"]);
        let py_dom_min = case["dom_min"].as_bool().unwrap();
        let py_dom_max = case["dom_max"].as_bool().unwrap();

        // Equal values: never dominates (irreflexive)
        let rs_dom_min = dominates(&[v], &[v], &[StudyDirection::Minimize]);
        let rs_dom_max = dominates(&[v], &[v], &[StudyDirection::Maximize]);

        assert_eq!(rs_dom_min, py_dom_min, "dom_1d_equal[{i}] minimize: v={v}");
        assert_eq!(rs_dom_max, py_dom_max, "dom_1d_equal[{i}] maximize: v={v}");
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  1b. dominates() — mixed direction 2D
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn deep_cv_dominates_mixed_direction() {
    // Minimize obj0, Maximize obj1
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Maximize];

    // a=[1,3], b=[2,2]: a better in both (lower-min, higher-max) → dominates
    assert!(dominates(&[1.0, 3.0], &[2.0, 2.0], &dirs));
    // reverse: b does NOT dominate a
    assert!(!dominates(&[2.0, 2.0], &[1.0, 3.0], &dirs));
    // trade-off: a=[1,2], b=[2,3]: a better in obj0(min), b better in obj1(max) → neither
    assert!(!dominates(&[1.0, 2.0], &[2.0, 3.0], &dirs));
    assert!(!dominates(&[2.0, 3.0], &[1.0, 2.0], &dirs));
    // equal in one, better in other: a=[1,3], b=[1,2] → a dominates (same min, better max)
    assert!(dominates(&[1.0, 3.0], &[1.0, 2.0], &dirs));
    assert!(!dominates(&[1.0, 2.0], &[1.0, 3.0], &dirs));
}

#[test]
fn deep_cv_dominates_inf_values() {
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];
    // -inf dominates finite
    assert!(dominates(&[f64::NEG_INFINITY, 1.0], &[0.0, 1.0], &dirs));
    // finite dominates inf
    assert!(dominates(&[0.0, 1.0], &[f64::INFINITY, 1.0], &dirs));
    // -inf vs inf
    assert!(dominates(
        &[f64::NEG_INFINITY],
        &[f64::INFINITY],
        &[StudyDirection::Minimize]
    ));
    // inf vs -inf for maximize
    assert!(dominates(
        &[f64::INFINITY],
        &[f64::NEG_INFINITY],
        &[StudyDirection::Maximize]
    ));
}

// ═══════════════════════════════════════════════════════════════════════════
//  2. fast_non_dominated_sort — Python _fast_non_domination_rank exact match
// ═══════════════════════════════════════════════════════════════════════════

/// Test all parametrized cases from Python test_fast_non_domination_rank
#[test]
fn deep_cv_fns_rank_cases() {
    let b = load();
    let cases = b["fns_rank_cases"].as_array().unwrap();
    let dirs_min2 = vec![StudyDirection::Minimize, StudyDirection::Minimize];
    let dirs_min3 = vec![
        StudyDirection::Minimize,
        StudyDirection::Minimize,
        StudyDirection::Minimize,
    ];

    for (ci, case) in cases.iter().enumerate() {
        let values: Vec<Vec<f64>> = case["values"]
            .as_array()
            .unwrap()
            .iter()
            .map(|row| row.as_array().unwrap().iter().map(|v| v.as_f64().unwrap()).collect())
            .collect();
        let expected_ranks = ji64_vec(&case["expected_ranks"]);
        let n_obj = values[0].len();
        let dirs = if n_obj == 2 { &dirs_min2 } else { &dirs_min3 };

        let trials: Vec<FrozenTrial> = values
            .iter()
            .enumerate()
            .map(|(i, v)| make_trial(i as i64, v.clone()))
            .collect();
        let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
        let fronts = fast_non_dominated_sort(&trial_refs, dirs);
        let ranks = fronts_to_ranks(&fronts, trials.len());

        assert_eq!(
            ranks, expected_ranks,
            "fns_rank_cases[{ci}] values={values:?}"
        );
    }
}

#[test]
fn deep_cv_fns_many_fronts() {
    let b = load();
    let sec = &b["fns_many_fronts"];
    let values: Vec<Vec<f64>> = sec["values"]
        .as_array()
        .unwrap()
        .iter()
        .map(|row| row.as_array().unwrap().iter().map(|v| v.as_f64().unwrap()).collect())
        .collect();
    let expected_ranks = ji64_vec(&sec["ranks"]);
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];

    let trials: Vec<FrozenTrial> = values
        .iter()
        .enumerate()
        .map(|(i, v)| make_trial(i as i64, v.clone()))
        .collect();
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let fronts = fast_non_dominated_sort(&trial_refs, &dirs);
    let ranks = fronts_to_ranks(&fronts, trials.len());

    assert_eq!(ranks, expected_ranks, "fns_many_fronts");
    // Additionally verify front count
    assert_eq!(fronts.len(), 4, "should have 4 fronts");
}

#[test]
fn deep_cv_fns_mixed_direction() {
    let b = load();
    let sec = &b["fns_mixed_direction"];
    let values: Vec<Vec<f64>> = sec["values"]
        .as_array()
        .unwrap()
        .iter()
        .map(|row| row.as_array().unwrap().iter().map(|v| v.as_f64().unwrap()).collect())
        .collect();
    let expected_ranks = ji64_vec(&sec["ranks"]);

    // Python used: loss[:, 1] *= -1 for maximize.
    // Rust: we use Minimize/Maximize directions directly.
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Maximize];

    let trials: Vec<FrozenTrial> = values
        .iter()
        .enumerate()
        .map(|(i, v)| make_trial(i as i64, v.clone()))
        .collect();
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let fronts = fast_non_dominated_sort(&trial_refs, &dirs);
    let ranks = fronts_to_ranks(&fronts, trials.len());

    assert_eq!(ranks, expected_ranks, "fns_mixed_direction");
}

/// Verify duplicate handling: identical solutions should share rank=0
#[test]
fn deep_cv_fns_duplicates() {
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];
    // 3 identical solutions → all on front 0 (none dominates another)
    let trials: Vec<FrozenTrial> = (0..3)
        .map(|i| make_trial(i as i64, vec![1.0, 1.0]))
        .collect();
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let fronts = fast_non_dominated_sort(&trial_refs, &dirs);
    let ranks = fronts_to_ranks(&fronts, 3);
    assert_eq!(ranks, vec![0, 0, 0], "all duplicates should be rank 0");
}

/// Python test case: 7 trials with duplicates (2D)
#[test]
fn deep_cv_fns_duplicates_with_dominated() {
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];
    // [[1,1],[1,1],[1,2],[2,1],[1,1],[0,1.5],[0,1.5]]
    // Expected: [0,0,1,1,0,0,0]
    let values = vec![
        vec![1.0, 1.0],
        vec![1.0, 1.0],
        vec![1.0, 2.0],
        vec![2.0, 1.0],
        vec![1.0, 1.0],
        vec![0.0, 1.5],
        vec![0.0, 1.5],
    ];
    let trials: Vec<FrozenTrial> = values
        .iter()
        .enumerate()
        .map(|(i, v)| make_trial(i as i64, v.clone()))
        .collect();
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let fronts = fast_non_dominated_sort(&trial_refs, &dirs);
    let ranks = fronts_to_ranks(&fronts, trials.len());
    assert_eq!(ranks, vec![0, 0, 1, 1, 0, 0, 0]);
}

/// Python test case: 7 trials with duplicates (3D)
#[test]
fn deep_cv_fns_duplicates_3d() {
    let dirs = vec![
        StudyDirection::Minimize,
        StudyDirection::Minimize,
        StudyDirection::Minimize,
    ];
    let values = vec![
        vec![1.0, 1.0, 1.0],
        vec![1.0, 1.0, 1.0],
        vec![1.0, 1.0, 2.0],
        vec![1.0, 2.0, 1.0],
        vec![2.0, 1.0, 1.0],
        vec![0.0, 1.5, 1.5],
        vec![0.0, 1.5, 1.5],
    ];
    let trials: Vec<FrozenTrial> = values
        .iter()
        .enumerate()
        .map(|(i, v)| make_trial(i as i64, v.clone()))
        .collect();
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let fronts = fast_non_dominated_sort(&trial_refs, &dirs);
    let ranks = fronts_to_ranks(&fronts, trials.len());
    assert_eq!(ranks, vec![0, 0, 1, 1, 1, 0, 0]);
}

// ═══════════════════════════════════════════════════════════════════════════
//  3. crowding_distance — Python-exact values
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn deep_cv_cd_1d_cases() {
    let b = load();
    let cases = b["cd_python_exact"].as_array().unwrap();

    for (ci, case) in cases.iter().enumerate() {
        let values: Vec<Vec<f64>> = case["values"]
            .as_array()
            .unwrap()
            .iter()
            .map(|row| {
                row.as_array()
                    .unwrap()
                    .iter()
                    .map(jf64)
                    .collect()
            })
            .collect();
        let expected_dists = jf64_vec(&case["distances"]);

        let trials: Vec<FrozenTrial> = values
            .iter()
            .enumerate()
            .map(|(i, v)| make_trial(i as i64, v.clone()))
            .collect();
        let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
        let dirs: Vec<StudyDirection> = vec![StudyDirection::Minimize; values[0].len()];
        let cd = crowding_distance(&trial_refs, &dirs);

        assert_eq!(
            cd.len(),
            expected_dists.len(),
            "cd_python_exact[{ci}] length mismatch"
        );

        // Crowding distance doesn't depend on direction (it's per-index, not trial.number)
        // But Python uses trial.number as key. Since we create trials with number=index,
        // the mapping should align.
        // However, crowding_distance in Rust returns distances in trial_refs order,
        // while Python sorts by each objective. The final sum should be the same.
        for (j, (&got, &exp)) in cd.iter().zip(expected_dists.iter()).enumerate() {
            assert_close(got, exp, TOL, &format!("cd_python_exact[{ci}][{j}]"));
        }
    }
}

#[test]
fn deep_cv_cd_2d_cases() {
    let b = load();
    let cases = b["cd_2d_exact"].as_array().unwrap();

    for (ci, case) in cases.iter().enumerate() {
        let values: Vec<Vec<f64>> = case["values"]
            .as_array()
            .unwrap()
            .iter()
            .map(|row| row.as_array().unwrap().iter().map(|v| v.as_f64().unwrap()).collect())
            .collect();
        let expected_dists = jf64_vec(&case["distances"]);

        let trials: Vec<FrozenTrial> = values
            .iter()
            .enumerate()
            .map(|(i, v)| make_trial(i as i64, v.clone()))
            .collect();
        let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
        let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];
        let cd = crowding_distance(&trial_refs, &dirs);

        for (j, (&got, &exp)) in cd.iter().zip(expected_dists.iter()).enumerate() {
            assert_close(got, exp, TOL, &format!("cd_2d_exact[{ci}][{j}]"));
        }
    }
}

#[test]
fn deep_cv_cd_3d_5points() {
    let b = load();
    let sec = &b["cd_3d_5points"];
    let values: Vec<Vec<f64>> = sec["values"]
        .as_array()
        .unwrap()
        .iter()
        .map(|row| row.as_array().unwrap().iter().map(|v| v.as_f64().unwrap()).collect())
        .collect();
    let expected_dists = jf64_vec(&sec["distances"]);

    let trials: Vec<FrozenTrial> = values
        .iter()
        .enumerate()
        .map(|(i, v)| make_trial(i as i64, v.clone()))
        .collect();
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let dirs = vec![
        StudyDirection::Minimize,
        StudyDirection::Minimize,
        StudyDirection::Minimize,
    ];
    let cd = crowding_distance(&trial_refs, &dirs);

    for (j, (&got, &exp)) in cd.iter().zip(expected_dists.iter()).enumerate() {
        assert_close(got, exp, TOL, &format!("cd_3d_5points[{j}]"));
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  3b. crowding_distance sort order — matches Python _crowding_distance_sort
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn deep_cv_cd_sort_order() {
    let b = load();
    let cases = b["cd_sort_order"].as_array().unwrap();

    for (ci, case) in cases.iter().enumerate() {
        let values: Vec<Vec<f64>> = case["values"]
            .as_array()
            .unwrap()
            .iter()
            .map(|row| row.as_array().unwrap().iter().map(jf64).collect())
            .collect();
        let expected_dists = jf64_vec(&case["distances"]);
        let expected_sorted: Vec<i64> = case["sorted_indices"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_i64().unwrap())
            .collect();

        let trials: Vec<FrozenTrial> = values
            .iter()
            .enumerate()
            .map(|(i, v)| make_trial(i as i64, v.clone()))
            .collect();
        let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
        let dirs: Vec<StudyDirection> = vec![StudyDirection::Minimize; values[0].len()];
        let cd = crowding_distance(&trial_refs, &dirs);

        // Check distances match
        for (j, (&got, &exp)) in cd.iter().zip(expected_dists.iter()).enumerate() {
            assert_close(got, exp, TOL, &format!("cd_sort[{ci}][{j}]"));
        }

        // Check sort order (descending by distance)
        let mut indices: Vec<usize> = (0..cd.len()).collect();
        indices.sort_by(|&a, &b| cd[b].partial_cmp(&cd[a]).unwrap_or(std::cmp::Ordering::Equal));
        let sorted_i64: Vec<i64> = indices.iter().map(|&i| i as i64).collect();
        assert_eq!(
            sorted_i64, expected_sorted,
            "cd_sort_order[{ci}] sort mismatch"
        );
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  4. is_pareto_front — Python _is_pareto_front exact match
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn deep_cv_pareto_front_cases() {
    let b = load();
    let cases = b["pareto_front_cases"].as_array().unwrap();

    for (ci, case) in cases.iter().enumerate() {
        let values: Vec<Vec<f64>> = case["values"]
            .as_array()
            .unwrap()
            .iter()
            .map(|row| row.as_array().unwrap().iter().map(|v| v.as_f64().unwrap()).collect())
            .collect();
        let expected_front: Vec<bool> = case["on_front"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_bool().unwrap())
            .collect();

        let trials: Vec<FrozenTrial> = values
            .iter()
            .enumerate()
            .map(|(i, v)| make_trial(i as i64, v.clone()))
            .collect();
        let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
        let dirs = vec![StudyDirection::Minimize; values[0].len()];
        let front = is_pareto_front(&trial_refs, &dirs);

        assert_eq!(
            front, expected_front,
            "pareto_front_cases[{ci}] values={values:?}"
        );
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  5. Large problem — 10 trials, 3 objectives, full pipeline
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn deep_cv_large_3obj_ranks() {
    let b = load();
    let sec = &b["large_3obj"];
    let values: Vec<Vec<f64>> = sec["values"]
        .as_array()
        .unwrap()
        .iter()
        .map(|row| row.as_array().unwrap().iter().map(|v| v.as_f64().unwrap()).collect())
        .collect();
    let expected_ranks = ji64_vec(&sec["ranks"]);

    let dirs = vec![
        StudyDirection::Minimize,
        StudyDirection::Minimize,
        StudyDirection::Minimize,
    ];
    let trials: Vec<FrozenTrial> = values
        .iter()
        .enumerate()
        .map(|(i, v)| make_trial(i as i64, v.clone()))
        .collect();
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let fronts = fast_non_dominated_sort(&trial_refs, &dirs);
    let ranks = fronts_to_ranks(&fronts, trials.len());

    assert_eq!(ranks, expected_ranks, "large_3obj ranks");
}

#[test]
fn deep_cv_large_3obj_front0_cd() {
    let b = load();
    let sec = &b["large_3obj"];
    let values: Vec<Vec<f64>> = sec["values"]
        .as_array()
        .unwrap()
        .iter()
        .map(|row| row.as_array().unwrap().iter().map(|v| v.as_f64().unwrap()).collect())
        .collect();
    let expected_ranks = ji64_vec(&sec["ranks"]);
    let expected_cd = &sec["front0_cd"];

    let dirs = vec![
        StudyDirection::Minimize,
        StudyDirection::Minimize,
        StudyDirection::Minimize,
    ];
    let trials: Vec<FrozenTrial> = values
        .iter()
        .enumerate()
        .map(|(i, v)| make_trial(i as i64, v.clone()))
        .collect();

    // Extract front 0 trials
    let front0_indices: Vec<usize> = expected_ranks
        .iter()
        .enumerate()
        .filter(|&(_, &r)| r == 0)
        .map(|(i, _)| i)
        .collect();

    let front0_trials: Vec<&FrozenTrial> =
        front0_indices.iter().map(|&i| &trials[i]).collect();
    let cd = crowding_distance(&front0_trials, &dirs);

    for (j, &idx) in front0_indices.iter().enumerate() {
        let key = idx.to_string();
        let exp = jf64(&expected_cd[&key]);
        assert_close(
            cd[j],
            exp,
            TOL,
            &format!("large_3obj front0_cd[trial {idx}]"),
        );
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  6. Algorithmic properties — invariants that must ALWAYS hold
// ═══════════════════════════════════════════════════════════════════════════

/// Antisymmetry: if a dominates b, then b does NOT dominate a
#[test]
fn deep_cv_dominates_antisymmetry() {
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];
    let test_pairs = vec![
        (vec![1.0, 2.0], vec![2.0, 3.0]),
        (vec![0.0, 0.0], vec![1.0, 1.0]),
        (vec![1.0, 1.0], vec![1.0, 2.0]),
    ];
    for (a, b) in test_pairs {
        if dominates(&a, &b, &dirs) {
            assert!(!dominates(&b, &a, &dirs), "antisymmetry violated: a={a:?} b={b:?}");
        }
    }
}

/// Irreflexivity: a does NOT dominate itself
#[test]
fn deep_cv_dominates_irreflexive() {
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Maximize];
    let vals = vec![
        vec![1.0, 2.0],
        vec![0.0, 0.0],
        vec![f64::INFINITY, f64::NEG_INFINITY],
    ];
    for v in vals {
        assert!(!dominates(&v, &v, &dirs), "irreflexivity violated: v={v:?}");
    }
}

/// Transitivity: if a dom b and b dom c, then a dom c
#[test]
fn deep_cv_dominates_transitivity() {
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];
    let a = vec![1.0, 1.0];
    let b = vec![2.0, 2.0];
    let c = vec![3.0, 3.0];
    assert!(dominates(&a, &b, &dirs));
    assert!(dominates(&b, &c, &dirs));
    assert!(dominates(&a, &c, &dirs), "transitivity violated");
}

/// Front 0 is non-empty for non-empty input
#[test]
fn deep_cv_fns_front0_nonempty() {
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];
    for n in 1..=5 {
        let trials: Vec<FrozenTrial> = (0..n)
            .map(|i| make_trial(i as i64, vec![i as f64, (n - i) as f64]))
            .collect();
        let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
        let fronts = fast_non_dominated_sort(&trial_refs, &dirs);
        assert!(!fronts.is_empty(), "fronts empty for n={n}");
        assert!(!fronts[0].is_empty(), "front0 empty for n={n}");
    }
}

/// All trials are assigned exactly one rank
#[test]
fn deep_cv_fns_complete_partition() {
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];
    let trials: Vec<FrozenTrial> = vec![
        make_trial(0, vec![1.0, 4.0]),
        make_trial(1, vec![2.0, 3.0]),
        make_trial(2, vec![3.0, 2.0]),
        make_trial(3, vec![4.0, 4.0]),
        make_trial(4, vec![5.0, 5.0]),
    ];
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let fronts = fast_non_dominated_sort(&trial_refs, &dirs);

    let total: usize = fronts.iter().map(|f| f.len()).sum();
    assert_eq!(total, trials.len(), "not all trials assigned");

    // Each index appears exactly once
    let mut seen = vec![false; trials.len()];
    for front in &fronts {
        for &idx in front {
            assert!(!seen[idx], "index {idx} appears in multiple fronts");
            seen[idx] = true;
        }
    }
}

/// Within a front, no solution dominates another
#[test]
fn deep_cv_fns_no_intra_front_dominance() {
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];
    let trials: Vec<FrozenTrial> = vec![
        make_trial(0, vec![1.0, 6.0]),
        make_trial(1, vec![2.0, 5.0]),
        make_trial(2, vec![3.0, 4.0]),
        make_trial(3, vec![2.0, 6.0]),
        make_trial(4, vec![3.0, 5.0]),
        make_trial(5, vec![4.0, 4.0]),
        make_trial(6, vec![5.0, 6.0]),
        make_trial(7, vec![6.0, 5.0]),
        make_trial(8, vec![7.0, 7.0]),
    ];
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let fronts = fast_non_dominated_sort(&trial_refs, &dirs);

    for (r, front) in fronts.iter().enumerate() {
        for &i in front {
            for &j in front {
                if i == j {
                    continue;
                }
                let vi = trials[i].values.as_ref().unwrap();
                let vj = trials[j].values.as_ref().unwrap();
                assert!(
                    !dominates(vi, vj, &dirs),
                    "front {r}: trial {i} dominates trial {j}"
                );
            }
        }
    }
}

/// Crowding distance is non-negative
#[test]
fn deep_cv_cd_non_negative() {
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];
    let trials: Vec<FrozenTrial> = (0..10)
        .map(|i| make_trial(i, vec![i as f64 * 1.5, 10.0 - i as f64]))
        .collect();
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let cd = crowding_distance(&trial_refs, &dirs);
    for (i, &d) in cd.iter().enumerate() {
        assert!(d >= 0.0, "negative crowding distance at index {i}: {d}");
    }
}

/// With 2 trials, both get infinite crowding distance
#[test]
fn deep_cv_cd_two_trials_always_inf() {
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];
    for (a, b) in [(1.0, 2.0), (0.0, 100.0), (-1.0, 1.0)] {
        let trials = vec![
            make_trial(0, vec![a, b]),
            make_trial(1, vec![b, a]),
        ];
        let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
        let cd = crowding_distance(&trial_refs, &dirs);
        assert!(cd[0].is_infinite(), "2 trials: dist[0] should be inf, got {}", cd[0]);
        assert!(cd[1].is_infinite(), "2 trials: dist[1] should be inf, got {}", cd[1]);
    }
}
