// Cross-validation tests for NSGA-II multi-objective operations.
// Python reference values generated by tests/nsga_cross_validate_baseline.py.

use std::collections::HashMap;
use optuna_rs::multi_objective::{crowding_distance, fast_non_dominated_sort, dominates};
use optuna_rs::study::StudyDirection;
use optuna_rs::trial::{FrozenTrial, TrialState};

const TOL: f64 = 1e-10;

fn load_baseline() -> serde_json::Value {
    let data = include_str!("nsga_baseline_values.json");
    serde_json::from_str(data).expect("Failed to parse nsga baseline JSON")
}

fn get_f64(val: &serde_json::Value, key: &str) -> f64 {
    match &val[key] {
        serde_json::Value::Number(n) => n.as_f64().unwrap(),
        serde_json::Value::String(s) if s == "Infinity" => f64::INFINITY,
        serde_json::Value::String(s) if s == "-Infinity" => f64::NEG_INFINITY,
        serde_json::Value::String(s) if s == "NaN" => f64::NAN,
        v => panic!("Unexpected value for {key}: {v:?}"),
    }
}

fn get_f64_vec(val: &serde_json::Value, key: &str) -> Vec<f64> {
    val[key]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| match v {
            serde_json::Value::Number(n) => n.as_f64().unwrap(),
            serde_json::Value::String(s) if s == "Infinity" => f64::INFINITY,
            serde_json::Value::String(s) if s == "-Infinity" => f64::NEG_INFINITY,
            serde_json::Value::String(s) if s == "NaN" => f64::NAN,
            other => panic!("Unexpected value in {key}: {other:?}"),
        })
        .collect()
}

fn get_int_vec(val: &serde_json::Value, key: &str) -> Vec<i64> {
    val[key]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_i64().unwrap())
        .collect()
}

fn assert_close(got: f64, expected: f64, tol: f64, label: &str) {
    if expected.is_infinite() {
        assert!(
            got.is_infinite() && got.signum() == expected.signum(),
            "{label}: expected {expected}, got {got}"
        );
    } else if expected.is_nan() {
        assert!(got.is_nan(), "{label}: expected NaN, got {got}");
    } else {
        let diff = (got - expected).abs();
        let denom = expected.abs().max(1.0);
        assert!(
            diff / denom < tol,
            "{label}: expected {expected}, got {got}, rel_err = {:.2e}",
            diff / denom
        );
    }
}

fn make_trial(number: i64, values: Vec<f64>) -> FrozenTrial {
    FrozenTrial::new(
        number,
        TrialState::Complete,
        None,
        Some(values),
        Some(chrono::Utc::now()),
        Some(chrono::Utc::now()),
        HashMap::new(),
        HashMap::new(),
        HashMap::new(),
        HashMap::new(),
        HashMap::new(),
        number,
    )
    .unwrap()
}

// ═══════════════════════════════════════════════════════════════════════════
//  1. Crowding distance
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_crowding_distance_2d() {
    let b = load_baseline();
    let expected = get_f64_vec(&b, "cd_2d");

    let trials: Vec<FrozenTrial> = vec![
        make_trial(0, vec![1.0, 5.0]),
        make_trial(1, vec![2.0, 3.0]),
        make_trial(2, vec![3.0, 2.0]),
        make_trial(3, vec![4.0, 1.0]),
        make_trial(4, vec![5.0, 0.0]),
    ];
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];
    let cd = crowding_distance(&trial_refs, &dirs);

    for (i, (&got, &exp)) in cd.iter().zip(expected.iter()).enumerate() {
        assert_close(got, exp, TOL, &format!("cd_2d[{i}]"));
    }
}

#[test]
fn cv_crowding_distance_same_dim() {
    let b = load_baseline();
    let expected = get_f64_vec(&b, "cd_same_dim");

    let trials: Vec<FrozenTrial> = vec![
        make_trial(0, vec![1.0, 3.0]),
        make_trial(1, vec![1.0, 2.0]),
        make_trial(2, vec![1.0, 1.0]),
    ];
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];
    let cd = crowding_distance(&trial_refs, &dirs);

    for (i, (&got, &exp)) in cd.iter().zip(expected.iter()).enumerate() {
        assert_close(got, exp, TOL, &format!("cd_same_dim[{i}]"));
    }
}

#[test]
fn cv_crowding_distance_two() {
    let b = load_baseline();
    let expected = get_f64_vec(&b, "cd_two");

    let trials: Vec<FrozenTrial> = vec![
        make_trial(0, vec![1.0, 3.0]),
        make_trial(1, vec![3.0, 1.0]),
    ];
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];
    let cd = crowding_distance(&trial_refs, &dirs);

    for (i, (&got, &exp)) in cd.iter().zip(expected.iter()).enumerate() {
        assert_close(got, exp, TOL, &format!("cd_two[{i}]"));
    }
}

#[test]
fn cv_crowding_distance_one() {
    let b = load_baseline();
    let expected = get_f64_vec(&b, "cd_one");

    let trials: Vec<FrozenTrial> = vec![make_trial(0, vec![2.0, 2.0])];
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];
    let cd = crowding_distance(&trial_refs, &dirs);

    for (i, (&got, &exp)) in cd.iter().zip(expected.iter()).enumerate() {
        assert_close(got, exp, TOL, &format!("cd_one[{i}]"));
    }
}

#[test]
fn cv_crowding_distance_inf() {
    let b = load_baseline();
    let expected = get_f64_vec(&b, "cd_inf");

    let trials: Vec<FrozenTrial> = vec![
        make_trial(0, vec![1.0, f64::INFINITY]),
        make_trial(1, vec![2.0, 3.0]),
        make_trial(2, vec![3.0, 1.0]),
        make_trial(3, vec![f64::INFINITY, 0.5]),
    ];
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];
    let cd = crowding_distance(&trial_refs, &dirs);

    for (i, (&got, &exp)) in cd.iter().zip(expected.iter()).enumerate() {
        assert_close(got, exp, TOL, &format!("cd_inf[{i}]"));
    }
}

#[test]
fn cv_crowding_distance_3d() {
    let b = load_baseline();
    let expected = get_f64_vec(&b, "cd_3d");

    let trials: Vec<FrozenTrial> = vec![
        make_trial(0, vec![1.0, 5.0, 3.0]),
        make_trial(1, vec![2.0, 3.0, 4.0]),
        make_trial(2, vec![3.0, 2.0, 2.0]),
        make_trial(3, vec![4.0, 1.0, 1.0]),
    ];
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let dirs = vec![
        StudyDirection::Minimize,
        StudyDirection::Minimize,
        StudyDirection::Minimize,
    ];
    let cd = crowding_distance(&trial_refs, &dirs);

    for (i, (&got, &exp)) in cd.iter().zip(expected.iter()).enumerate() {
        assert_close(got, exp, TOL, &format!("cd_3d[{i}]"));
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  2. Non-dominated sort
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_nds_2d() {
    let b = load_baseline();
    let expected = get_int_vec(&b, "nds_ranks_2d");

    let trials: Vec<FrozenTrial> = vec![
        make_trial(0, vec![1.0, 4.0]),
        make_trial(1, vec![2.0, 2.0]),
        make_trial(2, vec![4.0, 1.0]),
        make_trial(3, vec![3.0, 3.0]),
        make_trial(4, vec![5.0, 5.0]),
    ];
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];
    let fronts = fast_non_dominated_sort(&trial_refs, &dirs);

    // Convert fronts to per-trial ranks
    let mut ranks = vec![0i64; trials.len()];
    for (rank, front) in fronts.iter().enumerate() {
        for &idx in front {
            ranks[idx] = rank as i64;
        }
    }

    assert_eq!(ranks, expected, "nds_ranks_2d mismatch");
}

#[test]
fn cv_nds_3d() {
    let b = load_baseline();
    let expected = get_int_vec(&b, "nds_ranks_3d");

    let trials: Vec<FrozenTrial> = vec![
        make_trial(0, vec![1.0, 3.0, 2.0]),
        make_trial(1, vec![2.0, 1.0, 3.0]),
        make_trial(2, vec![3.0, 2.0, 1.0]),
        make_trial(3, vec![2.0, 2.0, 2.0]),
        make_trial(4, vec![4.0, 4.0, 4.0]),
    ];
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let dirs = vec![
        StudyDirection::Minimize,
        StudyDirection::Minimize,
        StudyDirection::Minimize,
    ];
    let fronts = fast_non_dominated_sort(&trial_refs, &dirs);

    let mut ranks = vec![0i64; trials.len()];
    for (rank, front) in fronts.iter().enumerate() {
        for &idx in front {
            ranks[idx] = rank as i64;
        }
    }

    assert_eq!(ranks, expected, "nds_ranks_3d mismatch");
}

#[test]
fn cv_nds_same() {
    let b = load_baseline();
    let expected = get_int_vec(&b, "nds_ranks_same");

    let trials: Vec<FrozenTrial> = vec![
        make_trial(0, vec![1.0, 1.0]),
        make_trial(1, vec![1.0, 1.0]),
        make_trial(2, vec![1.0, 1.0]),
    ];
    let trial_refs: Vec<&FrozenTrial> = trials.iter().collect();
    let dirs = vec![StudyDirection::Minimize, StudyDirection::Minimize];
    let fronts = fast_non_dominated_sort(&trial_refs, &dirs);

    let mut ranks = vec![0i64; trials.len()];
    for (rank, front) in fronts.iter().enumerate() {
        for &idx in front {
            ranks[idx] = rank as i64;
        }
    }

    assert_eq!(ranks, expected, "nds_ranks_same mismatch");
}

// ═══════════════════════════════════════════════════════════════════════════
//  3. Dominates function
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_dominates_basic() {
    let dirs_min = vec![StudyDirection::Minimize, StudyDirection::Minimize];

    // [1, 2] dominates [2, 3]
    assert!(dominates(&[1.0, 2.0], &[2.0, 3.0], &dirs_min));
    // [2, 3] does NOT dominate [1, 2]
    assert!(!dominates(&[2.0, 3.0], &[1.0, 2.0], &dirs_min));
    // [1, 2] does NOT dominate [2, 1] (trade-off)
    assert!(!dominates(&[1.0, 2.0], &[2.0, 1.0], &dirs_min));
    // [1, 1] dominates [1, 2] (equal in first, better in second)
    assert!(dominates(&[1.0, 1.0], &[1.0, 2.0], &dirs_min));
    // [1, 1] does NOT dominate [1, 1] (identical)
    assert!(!dominates(&[1.0, 1.0], &[1.0, 1.0], &dirs_min));
}

#[test]
fn cv_dominates_maximize() {
    let dirs_max = vec![StudyDirection::Maximize, StudyDirection::Maximize];

    // [3, 3] dominates [2, 2] in maximize
    assert!(dominates(&[3.0, 3.0], &[2.0, 2.0], &dirs_max));
    // [2, 2] does NOT dominate [3, 3]
    assert!(!dominates(&[2.0, 2.0], &[3.0, 3.0], &dirs_max));
}
