//! TPE cross-validation tests: verify Rust matches Python reference values exactly.
//!
//! Reference values generated by `tests/tpe_cross_validate_baseline.py`
//! and stored in `tests/tpe_baseline_values.json`.

use indexmap::IndexMap;
use std::collections::HashMap;

use optuna_rs::distributions::*;
use optuna_rs::samplers::tpe::parzen_estimator::{
    default_gamma, default_weights, ParzenEstimator, ParzenEstimatorParameters,
};
use optuna_rs::samplers::tpe::truncnorm;

const TOL: f64 = 1e-8;
const NEWTON_TOL: f64 = 1e-5;

fn load_baseline() -> serde_json::Value {
    let data = include_str!("tpe_baseline_values.json");
    serde_json::from_str(data).expect("Failed to parse tpe_baseline_values.json")
}

fn get_f64(b: &serde_json::Value, key: &str) -> f64 {
    if let Some(v) = b[key].as_f64() {
        return v;
    }
    match b[key].as_str() {
        Some("-Infinity") => f64::NEG_INFINITY,
        Some("Infinity") => f64::INFINITY,
        _ => panic!("Key '{key}' not found or not a number"),
    }
}

fn get_f64_vec(b: &serde_json::Value, key: &str) -> Vec<f64> {
    b[key]
        .as_array()
        .unwrap_or_else(|| panic!("Key '{key}' not an array"))
        .iter()
        .map(|v| v.as_f64().unwrap())
        .collect()
}

fn assert_close(actual: f64, expected: f64, tol: f64, msg: &str) {
    if expected.is_infinite() {
        assert!(
            actual.is_infinite() && actual.signum() == expected.signum(),
            "{msg}: expected {expected}, got {actual}"
        );
        return;
    }
    if expected.is_nan() {
        assert!(actual.is_nan(), "{msg}: expected NaN, got {actual}");
        return;
    }
    let diff = (actual - expected).abs();
    let denom = expected.abs().max(1.0);
    assert!(
        diff / denom < tol,
        "{msg}: expected {expected}, got {actual}, diff={diff}"
    );
}

fn assert_vec_close(actual: &[f64], expected: &[f64], tol: f64, msg: &str) {
    assert_eq!(actual.len(), expected.len(), "{msg}: length {}, expected {}", actual.len(), expected.len());
    for (i, (&a, &e)) in actual.iter().zip(expected.iter()).enumerate() {
        assert_close(a, e, tol, &format!("{msg}[{i}]"));
    }
}

fn default_pe_params() -> ParzenEstimatorParameters {
    ParzenEstimatorParameters::default()
}

fn float_search_space(low: f64, high: f64, log: bool) -> IndexMap<String, Distribution> {
    let mut ss = IndexMap::new();
    ss.insert(
        "x".to_string(),
        Distribution::FloatDistribution(FloatDistribution::new(low, high, log, None).unwrap()),
    );
    ss
}

// ═══════════════════════════════════════════════════════════════════════════
//  1. ndtr — Normal CDF (including erfc-critical region)
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_ndtr() {
    let b = load_baseline();
    let cases: &[(f64, &str)] = &[
        (-6.0, "ndtr_-6.0"),
        (-3.0, "ndtr_-3.0"),
        (-1.0, "ndtr_-1.0"),
        (0.0, "ndtr_0.0"),
        (1.0, "ndtr_1.0"),
        (3.0, "ndtr_3.0"),
        (6.0, "ndtr_6.0"),
    ];
    for &(x, key) in cases {
        let py = get_f64(&b, key);
        let rust = 0.5 + 0.5 * libm::erf(x * std::f64::consts::FRAC_1_SQRT_2);
        assert_close(rust, py, TOL, &format!("ndtr({x})"));
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  1b. log_ndtr — Log Normal CDF precision
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_log_ndtr() {
    let b = load_baseline();
    let cases: &[(f64, &str)] = &[
        (-40.0, "log_ndtr_-40.0"),
        (-20.0, "log_ndtr_-20.0"),
        (-10.0, "log_ndtr_-10.0"),
        (-5.0, "log_ndtr_-5.0"),
        (-3.0, "log_ndtr_-3.0"),
        (-1.0, "log_ndtr_-1.0"),
        (0.0, "log_ndtr_0.0"),
        (1.0, "log_ndtr_1.0"),
        (3.0, "log_ndtr_3.0"),
        (6.0, "log_ndtr_6.0"),
        (10.0, "log_ndtr_10.0"),
    ];
    for &(x, key) in cases {
        let py = get_f64(&b, key);
        // log_ndtr is private, verify via log_gauss_mass(-inf, x) ≈ log_ndtr(x)
        // For very negative lower bound, log_gauss_mass(a, x) → log_ndtr(x)
        let rust = truncnorm::log_gauss_mass(-1e10, x);
        assert_close(rust, py, TOL, &format!("log_ndtr({x})"));
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  2. log_gauss_mass
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_log_gauss_mass() {
    let b = load_baseline();
    let cases: &[(f64, f64, &str)] = &[
        (-10.0, 10.0, "log_gauss_mass_-10.0_10.0"),
        (-10.0, 0.0, "log_gauss_mass_-10.0_0.0"),
        (0.0, 10.0, "log_gauss_mass_0.0_10.0"),
        (-1.0, 1.0, "log_gauss_mass_-1.0_1.0"),
        (-2.0, 2.0, "log_gauss_mass_-2.0_2.0"),
        (-3.0, -2.0, "log_gauss_mass_-3.0_-2.0"),
        (2.0, 3.0, "log_gauss_mass_2.0_3.0"),
        (-0.5, 0.5, "log_gauss_mass_-0.5_0.5"),
        (-30.0, -20.0, "log_gauss_mass_-30.0_-20.0"),
        (20.0, 30.0, "log_gauss_mass_20.0_30.0"),
        (-0.01, 0.01, "log_gauss_mass_-0.01_0.01"),
    ];
    for &(a, bb, key) in cases {
        let py = get_f64(&b, key);
        let rust = truncnorm::log_gauss_mass(a, bb);
        assert_close(rust, py, TOL, &format!("log_gauss_mass({a},{bb})"));
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  3. truncnorm logpdf
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_truncnorm_logpdf() {
    let b = load_baseline();
    // (x, a, b, loc, scale)
    let cases: &[(f64, f64, f64, f64, f64)] = &[
        (0.0, -1.0, 1.0, 0.0, 1.0),
        (0.5, -2.0, 2.0, 0.0, 1.0),
        (-0.5, -2.0, 2.0, 0.0, 1.0),
        (0.0, -10.0, 10.0, 0.0, 1.0),
        (5.0, 0.0, 10.0, 3.0, 2.0),
        (0.1, 0.0, 1.0, 0.5, 0.3),
        (0.99, 0.0, 1.0, 0.5, 0.3),
        (2.0, -1.0, 1.0, 0.0, 1.0),  // out of range
        (-2.0, -1.0, 1.0, 0.0, 1.0), // out of range
    ];
    for (i, &(x, a, bb, loc, scale)) in cases.iter().enumerate() {
        let key = format!("tn_logpdf_{i}");
        let py = get_f64(&b, &key);
        let rust = truncnorm::logpdf(x, a, bb, loc, scale);
        assert_close(rust, py, TOL, &format!("logpdf({x},[{a},{bb}],loc={loc},s={scale})"));
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  4. truncnorm PPF (percent point function / quantile)
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_truncnorm_ppf() {
    let b = load_baseline();
    // (q, a, b) — standardized (loc=0, scale=1)
    let cases: &[(f64, f64, f64)] = &[
        (0.0, -2.0, 2.0), (0.5, -2.0, 2.0), (1.0, -2.0, 2.0),
        (0.1, -1.0, 1.0), (0.25, -1.0, 1.0), (0.75, -1.0, 1.0), (0.9, -1.0, 1.0),
        (0.5, -10.0, 10.0), (0.01, -3.0, 3.0), (0.99, -3.0, 3.0),
        (0.5, 0.0, 5.0), (0.1, 1.0, 3.0), (0.9, 1.0, 3.0),
        (0.5, -5.0, 0.0), (0.1, -3.0, -1.0), (0.9, -3.0, -1.0),
        (0.001, -5.0, 5.0), (0.999, -5.0, 5.0),
    ];
    for (i, &(q, a, bb)) in cases.iter().enumerate() {
        let key = format!("tn_ppf_{i}");
        let py = get_f64(&b, &key);
        let rust = truncnorm::ppf(q, a, bb);
        assert_close(rust, py, NEWTON_TOL, &format!("ppf({q},{a},{bb})"));
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  5. ParzenEstimator — float kernels (mus, sigmas, weights)
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_pe_float_kernels() {
    let b = load_baseline();
    let ss = float_search_space(0.0, 10.0, false);
    let mut obs = HashMap::new();
    obs.insert("x".to_string(), vec![2.0, 5.0, 8.0]);
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    // Weights
    let py_w = get_f64_vec(&b, "pe_float_weights");
    assert_vec_close(pe.weights(), &py_w, TOL, "pe_float_weights");

    // Mus & sigmas
    let (mus, sigmas, _, _) = pe.numerical_kernels("x").unwrap();
    let py_mus = get_f64_vec(&b, "pe_float_mus");
    let py_sig = get_f64_vec(&b, "pe_float_sigmas");
    assert_vec_close(&mus, &py_mus, TOL, "pe_float_mus");
    assert_vec_close(&sigmas, &py_sig, TOL, "pe_float_sigmas");
}

#[test]
fn cv_pe_float_empty() {
    let b = load_baseline();
    let ss = float_search_space(0.0, 10.0, false);
    let obs: HashMap<String, Vec<f64>> = HashMap::new();
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    let py_w = get_f64_vec(&b, "pe_float_empty_weights");
    assert_vec_close(pe.weights(), &py_w, TOL, "pe_float_empty_weights");

    let (mus, sigmas, _, _) = pe.numerical_kernels("x").unwrap();
    let py_mus = get_f64_vec(&b, "pe_float_empty_mus");
    let py_sig = get_f64_vec(&b, "pe_float_empty_sigmas");
    assert_vec_close(&mus, &py_mus, TOL, "pe_float_empty_mus");
    assert_vec_close(&sigmas, &py_sig, TOL, "pe_float_empty_sigmas");
}

// ═══════════════════════════════════════════════════════════════════════════
//  6. ParzenEstimator — log-scale float kernels
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_pe_log_kernels() {
    let b = load_baseline();
    let mut ss = IndexMap::new();
    ss.insert(
        "lr".to_string(),
        Distribution::FloatDistribution(FloatDistribution::new(0.001, 1.0, true, None).unwrap()),
    );
    let mut obs = HashMap::new();
    obs.insert("lr".to_string(), vec![0.01, 0.1]);
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    let (mus, sigmas, _, _) = pe.numerical_kernels("lr").unwrap();
    let py_mus = get_f64_vec(&b, "pe_log_mus");
    let py_sig = get_f64_vec(&b, "pe_log_sigmas");
    assert_vec_close(&mus, &py_mus, TOL, "pe_log_mus");
    assert_vec_close(&sigmas, &py_sig, TOL, "pe_log_sigmas");
}

// ═══════════════════════════════════════════════════════════════════════════
//  7. ParzenEstimator — int with step
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_pe_int_step_kernels() {
    let b = load_baseline();
    let mut ss = IndexMap::new();
    ss.insert(
        "n".to_string(),
        Distribution::IntDistribution(IntDistribution::new(0, 10, false, 2).unwrap()),
    );
    let mut obs = HashMap::new();
    obs.insert("n".to_string(), vec![2.0, 4.0, 6.0]);
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    let (mus, sigmas, _, _) = pe.numerical_kernels("n").unwrap();
    let py_mus = get_f64_vec(&b, "pe_int_step_mus");
    let py_sig = get_f64_vec(&b, "pe_int_step_sigmas");
    assert_vec_close(&mus, &py_mus, TOL, "pe_int_step_mus");
    assert_vec_close(&sigmas, &py_sig, TOL, "pe_int_step_sigmas");
}

// ═══════════════════════════════════════════════════════════════════════════
//  8. ParzenEstimator — int log-scale
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_pe_int_log_kernels() {
    let b = load_baseline();
    let mut ss = IndexMap::new();
    ss.insert(
        "x".to_string(),
        Distribution::IntDistribution(IntDistribution::new(1, 100, true, 1).unwrap()),
    );
    let mut obs = HashMap::new();
    obs.insert("x".to_string(), vec![10.0, 20.0, 50.0]);
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    let (mus, sigmas, _, _) = pe.numerical_kernels("x").unwrap();
    let py_mus = get_f64_vec(&b, "pe_int_log_mus");
    let py_sig = get_f64_vec(&b, "pe_int_log_sigmas");
    assert_vec_close(&mus, &py_mus, TOL, "pe_int_log_mus");
    assert_vec_close(&sigmas, &py_sig, TOL, "pe_int_log_sigmas");
}

// ═══════════════════════════════════════════════════════════════════════════
//  9. log_pdf — float
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_logpdf_float() {
    let b = load_baseline();
    let ss = float_search_space(0.0, 10.0, false);
    let mut obs = HashMap::new();
    obs.insert("x".to_string(), vec![2.0, 5.0, 8.0]);
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    let samples = HashMap::from([("x".to_string(), vec![1.0, 3.0, 5.0, 7.0, 9.0])]);
    let rust = pe.log_pdf(&samples);
    let py = get_f64_vec(&b, "pe_logpdf_float");
    assert_vec_close(&rust, &py, TOL, "pe_logpdf_float");
}

// ═══════════════════════════════════════════════════════════════════════════
//  10. log_pdf — log-scale float
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_logpdf_log() {
    let b = load_baseline();
    let mut ss = IndexMap::new();
    ss.insert(
        "lr".to_string(),
        Distribution::FloatDistribution(FloatDistribution::new(0.001, 1.0, true, None).unwrap()),
    );
    let mut obs = HashMap::new();
    obs.insert("lr".to_string(), vec![0.01, 0.1]);
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    let samples = HashMap::from([(
        "lr".to_string(),
        vec![0.001, 0.01, 0.05, 0.1, 0.5, 1.0],
    )]);
    let rust = pe.log_pdf(&samples);
    let py = get_f64_vec(&b, "pe_logpdf_log");
    assert_vec_close(&rust, &py, NEWTON_TOL, "pe_logpdf_log");
}

// ═══════════════════════════════════════════════════════════════════════════
//  11. log_pdf — int with step
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_logpdf_int_step() {
    let b = load_baseline();
    let mut ss = IndexMap::new();
    ss.insert(
        "n".to_string(),
        Distribution::IntDistribution(IntDistribution::new(0, 10, false, 2).unwrap()),
    );
    let mut obs = HashMap::new();
    obs.insert("n".to_string(), vec![2.0, 4.0, 6.0]);
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    let samples = HashMap::from([("n".to_string(), vec![0.0, 2.0, 4.0, 6.0, 8.0, 10.0])]);
    let rust = pe.log_pdf(&samples);
    let py = get_f64_vec(&b, "pe_logpdf_int_step");
    assert_vec_close(&rust, &py, NEWTON_TOL, "pe_logpdf_int_step");
}

// ═══════════════════════════════════════════════════════════════════════════
//  12. log_pdf — int log-scale
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_logpdf_int_log() {
    let b = load_baseline();
    let mut ss = IndexMap::new();
    ss.insert(
        "x".to_string(),
        Distribution::IntDistribution(IntDistribution::new(1, 100, true, 1).unwrap()),
    );
    let mut obs = HashMap::new();
    obs.insert("x".to_string(), vec![10.0, 20.0, 50.0]);
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    let samples = HashMap::from([("x".to_string(), vec![1.0, 10.0, 20.0, 50.0, 100.0])]);
    let rust = pe.log_pdf(&samples);
    let py = get_f64_vec(&b, "pe_logpdf_int_log");
    assert_vec_close(&rust, &py, NEWTON_TOL, "pe_logpdf_int_log");
}

// ═══════════════════════════════════════════════════════════════════════════
//  13. Categorical — kernel weights & log_pdf
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_pe_categorical() {
    let b = load_baseline();
    let mut ss = IndexMap::new();
    ss.insert(
        "opt".to_string(),
        Distribution::CategoricalDistribution(
            CategoricalDistribution::new(vec![
                CategoricalChoice::Str("a".into()),
                CategoricalChoice::Str("b".into()),
                CategoricalChoice::Str("c".into()),
            ])
            .unwrap(),
        ),
    );

    // Empty observation
    {
        let obs: HashMap<String, Vec<f64>> = HashMap::new();
        let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);
        let cat_w = pe.categorical_kernels("opt").unwrap();
        let py_empty: Vec<Vec<f64>> = b["pe_cat_empty_weights"]
            .as_array()
            .unwrap()
            .iter()
            .map(|row| row.as_array().unwrap().iter().map(|v| v.as_f64().unwrap()).collect())
            .collect();
        assert_eq!(cat_w.len(), py_empty.len(), "cat_empty kernel count");
        for (i, (r, p)) in cat_w.iter().zip(py_empty.iter()).enumerate() {
            assert_vec_close(r, p, TOL, &format!("cat_empty_weights[{i}]"));
        }
    }

    // With observations [0, 0, 1]
    {
        let mut obs = HashMap::new();
        obs.insert("opt".to_string(), vec![0.0, 0.0, 1.0]);
        let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

        let cat_w = pe.categorical_kernels("opt").unwrap();
        let py_obs: Vec<Vec<f64>> = b["pe_cat_obs_weights"]
            .as_array()
            .unwrap()
            .iter()
            .map(|row| row.as_array().unwrap().iter().map(|v| v.as_f64().unwrap()).collect())
            .collect();
        assert_eq!(cat_w.len(), py_obs.len(), "cat_obs kernel count");
        for (i, (r, p)) in cat_w.iter().zip(py_obs.iter()).enumerate() {
            assert_vec_close(r, p, TOL, &format!("cat_obs_weights[{i}]"));
        }

        // log_pdf
        let samples = HashMap::from([("opt".to_string(), vec![0.0, 1.0, 2.0])]);
        let rust = pe.log_pdf(&samples);
        let py = get_f64_vec(&b, "pe_cat_logpdf");
        assert_vec_close(&rust, &py, TOL, "pe_cat_logpdf");
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  14. default_weights — exact match
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_default_weights() {
    let b = load_baseline();
    for n in [0, 1, 5, 10, 24, 25, 26, 30, 50, 100] {
        let key = format!("default_weights_{n}");
        let py = get_f64_vec(&b, &key);
        let rust = default_weights(n);
        assert_vec_close(&rust, &py, TOL, &format!("default_weights({n})"));
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  15. default_gamma — exact match
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_default_gamma() {
    let b = load_baseline();
    for n in [0usize, 1, 5, 10, 20, 50, 100, 200, 250, 300, 1000] {
        let key = format!("default_gamma_{n}");
        let py = b[&key].as_u64().unwrap() as usize;
        let rust = default_gamma(n);
        assert_eq!(rust, py, "default_gamma({n}): rust={rust}, py={py}");
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  16. Predetermined weights (MOTPE-style)
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_pe_predetermined_weights() {
    let b = load_baseline();
    let ss = float_search_space(0.0, 10.0, false);
    let mut obs = HashMap::new();
    obs.insert("x".to_string(), vec![2.0, 5.0, 8.0]);
    let pw = vec![0.5, 0.3, 0.2];
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), Some(&pw), None);

    let py = get_f64_vec(&b, "pe_predetermined_weights");
    assert_vec_close(pe.weights(), &py, TOL, "pe_predetermined_weights");
}

// ═══════════════════════════════════════════════════════════════════════════
//  17. Close observations — sigma clipping
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_pe_close_observations() {
    let b = load_baseline();
    let ss = float_search_space(0.0, 10.0, false);
    let mut obs = HashMap::new();
    obs.insert("x".to_string(), vec![5.0, 5.0, 5.0]);
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    let (mus, sigmas, _, _) = pe.numerical_kernels("x").unwrap();
    let py_mus = get_f64_vec(&b, "pe_close_obs_mus");
    let py_sig = get_f64_vec(&b, "pe_close_obs_sigmas");
    assert_vec_close(&mus, &py_mus, TOL, "pe_close_obs_mus");
    assert_vec_close(&sigmas, &py_sig, TOL, "pe_close_obs_sigmas");

    // log_pdf should be finite
    let samples = HashMap::from([("x".to_string(), vec![4.0, 5.0, 6.0])]);
    let logpdf: Vec<f64> = pe.log_pdf(&samples);
    for v in &logpdf {
        assert!(v.is_finite(), "log_pdf should be finite for close obs");
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  18. Single observation — sigma = range / (n_obs + 2)
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_pe_single_observation() {
    let b = load_baseline();
    let ss = float_search_space(0.0, 10.0, false);
    let mut obs = HashMap::new();
    obs.insert("x".to_string(), vec![5.0]);
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    let (_, sigmas, _, _) = pe.numerical_kernels("x").unwrap();
    let py_sig = get_f64_vec(&b, "pe_single_obs_sigmas");
    assert_vec_close(&sigmas, &py_sig, TOL, "pe_single_obs_sigmas");
}

// ═══════════════════════════════════════════════════════════════════════════
//  19. consider_endpoints = true
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_pe_consider_endpoints() {
    let b = load_baseline();
    let ss = float_search_space(0.0, 10.0, false);
    let mut obs = HashMap::new();
    obs.insert("x".to_string(), vec![2.0, 5.0, 8.0]);
    let mut params = default_pe_params();
    params.consider_endpoints = true;
    let pe = ParzenEstimator::new(&obs, &ss, &params, None, None);

    let (_, sigmas, _, _) = pe.numerical_kernels("x").unwrap();
    let py_sig = get_f64_vec(&b, "pe_endpoints_sigmas");
    assert_vec_close(&sigmas, &py_sig, TOL, "pe_endpoints_sigmas");
}

// ═══════════════════════════════════════════════════════════════════════════
//  20. consider_magic_clip = false
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_pe_no_magic_clip() {
    let b = load_baseline();
    let ss = float_search_space(0.0, 10.0, false);
    let mut obs = HashMap::new();
    obs.insert("x".to_string(), vec![2.0, 5.0, 8.0]);
    let mut params = default_pe_params();
    params.consider_magic_clip = false;
    let pe = ParzenEstimator::new(&obs, &ss, &params, None, None);

    let (_, sigmas, _, _) = pe.numerical_kernels("x").unwrap();
    let py_sig = get_f64_vec(&b, "pe_nomagicclip_sigmas");
    assert_vec_close(&sigmas, &py_sig, TOL, "pe_nomagicclip_sigmas");
}

// ═══════════════════════════════════════════════════════════════════════════
//  21. Multivariate sigma
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_pe_multivariate() {
    let b = load_baseline();
    let mut ss = IndexMap::new();
    ss.insert(
        "x".to_string(),
        Distribution::FloatDistribution(FloatDistribution::new(0.0, 10.0, false, None).unwrap()),
    );
    ss.insert(
        "y".to_string(),
        Distribution::FloatDistribution(FloatDistribution::new(-5.0, 5.0, false, None).unwrap()),
    );
    let mut obs = HashMap::new();
    obs.insert("x".to_string(), vec![2.0, 5.0, 8.0]);
    obs.insert("y".to_string(), vec![-1.0, 0.0, 3.0]);
    let mut params = default_pe_params();
    params.multivariate = true;
    let pe = ParzenEstimator::new(&obs, &ss, &params, None, None);

    let (_, x_sigmas, _, _) = pe.numerical_kernels("x").unwrap();
    let (_, y_sigmas, _, _) = pe.numerical_kernels("y").unwrap();
    let py_xs = get_f64_vec(&b, "pe_multi_x_sigmas");
    let py_ys = get_f64_vec(&b, "pe_multi_y_sigmas");
    assert_vec_close(&x_sigmas, &py_xs, TOL, "pe_multi_x_sigmas");
    assert_vec_close(&y_sigmas, &py_ys, TOL, "pe_multi_y_sigmas");
}

// ═══════════════════════════════════════════════════════════════════════════
//  22. Logsumexp numerical stability at extreme positions
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_logsumexp_stability() {
    let ss = float_search_space(0.0, 10.0, false);
    let mut obs = HashMap::new();
    obs.insert("x".to_string(), vec![2.0, 5.0, 8.0]);
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    let extreme = HashMap::from([("x".to_string(), vec![0.001, 9.999, 5.0])]);
    let logpdf: Vec<f64> = pe.log_pdf(&extreme);
    for (i, v) in logpdf.iter().enumerate() {
        assert!(v.is_finite(), "log_pdf[{i}] should be finite at extremes, got {v}");
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  23. PPF tight tolerance — near-boundary quantiles (tests ndtri_exp fix)
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_ppf_tight() {
    let b = load_baseline();
    // (q, a, b)
    let cases: &[(f64, f64, f64)] = &[
        (0.5, -0.5, 0.5),
        (0.001, -0.5, 0.5),
        (0.999, -0.5, 0.5),
        (0.5, -20.0, -10.0),
        (0.5, 10.0, 20.0),
        (0.001, -20.0, 20.0),
        (0.999, -20.0, 20.0),
        (1e-6, -5.0, 5.0),
        (1.0 - 1e-6, -5.0, 5.0),
    ];
    for (i, &(q, a, bb)) in cases.iter().enumerate() {
        let key = format!("tn_ppf_tight_{i}");
        let py = get_f64(&b, &key);
        let rust = truncnorm::ppf(q, a, bb);
        assert_close(rust, py, NEWTON_TOL, &format!("ppf_tight({q},{a},{bb})"));
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  24-30. TPE 端到端优化测试 — 验证收敛行为
// ═══════════════════════════════════════════════════════════════════════════

use std::sync::Arc;
use optuna_rs::samplers::{TpeSamplerBuilder, RandomSampler, Sampler};
use optuna_rs::study::{create_study, StudyDirection};

/// Python 参考: (x-3)^2, seed=42, 30 trials → best ≈ 0.022
#[test]
fn cv_tpe_quadratic_convergence() {
    let sampler = TpeSamplerBuilder::new(StudyDirection::Minimize)
        .seed(42)
        .n_startup_trials(5)
        .build();
    let study = create_study(
        None, Some(Arc::new(sampler) as Arc<dyn Sampler>),
        None, None, Some(StudyDirection::Minimize), None, false,
    ).unwrap();

    study.optimize(
        |trial| {
            let x = trial.suggest_float("x", -10.0, 10.0, false, None)?;
            Ok((x - 3.0).powi(2))
        },
        Some(30), None, None,
    ).unwrap();

    let best = study.best_trial().unwrap();
    let bv = best.values.as_ref().unwrap()[0];
    assert!(bv < 1.0, "TPE quadratic best should be < 1.0, got {bv}");
}

/// Rosenbrock 函数: TPE 50次内应找到合理值
#[test]
fn cv_tpe_rosenbrock() {
    let sampler = TpeSamplerBuilder::new(StudyDirection::Minimize)
        .seed(42).n_startup_trials(10).build();
    let study = create_study(
        None, Some(Arc::new(sampler) as Arc<dyn Sampler>),
        None, None, Some(StudyDirection::Minimize), None, false,
    ).unwrap();

    study.optimize(
        |trial| {
            let x = trial.suggest_float("x", -5.0, 5.0, false, None)?;
            let y = trial.suggest_float("y", -5.0, 5.0, false, None)?;
            Ok((1.0 - x).powi(2) + 100.0 * (y - x * x).powi(2))
        },
        Some(50), None, None,
    ).unwrap();

    let bv = study.best_trial().unwrap().values.as_ref().unwrap()[0];
    assert!(bv < 100.0, "TPE Rosenbrock best < 100, got {bv}");
}

/// TPE 最大化方向
#[test]
fn cv_tpe_maximize() {
    let sampler = TpeSamplerBuilder::new(StudyDirection::Maximize)
        .seed(42).n_startup_trials(5).build();
    let study = create_study(
        None, Some(Arc::new(sampler) as Arc<dyn Sampler>),
        None, None, Some(StudyDirection::Maximize), None, false,
    ).unwrap();

    study.optimize(
        |trial| {
            let x = trial.suggest_float("x", 0.0, 10.0, false, None)?;
            Ok(-(x - 10.0).powi(2))
        },
        Some(30), None, None,
    ).unwrap();

    let bv = study.best_trial().unwrap().values.as_ref().unwrap()[0];
    assert!(bv > -5.0, "TPE maximize should find > -5, got {bv}");
}

/// TPE 分类参数: 应学会选最佳类别
#[test]
fn cv_tpe_categorical() {
    let sampler = TpeSamplerBuilder::new(StudyDirection::Minimize)
        .seed(42).n_startup_trials(5).build();
    let study = create_study(
        None, Some(Arc::new(sampler) as Arc<dyn Sampler>),
        None, None, Some(StudyDirection::Minimize), None, false,
    ).unwrap();

    study.optimize(
        |trial| {
            let x = trial.suggest_float("x", 0.0, 10.0, false, None)?;
            let c = trial.suggest_categorical("c", vec![
                CategoricalChoice::Str("a".into()),
                CategoricalChoice::Str("b".into()),
                CategoricalChoice::Str("c".into()),
            ])?;
            let offset = match &c {
                CategoricalChoice::Str(s) => match s.as_str() {
                    "a" => 0.0, "b" => 5.0, "c" => 10.0, _ => 100.0,
                },
                _ => 100.0,
            };
            Ok((x - 3.0).powi(2) + offset)
        },
        Some(30), None, None,
    ).unwrap();

    let bv = study.best_trial().unwrap().values.as_ref().unwrap()[0];
    assert!(bv < 10.0, "TPE mixed best < 10, got {bv}");
}

/// TPE 整数参数优化
#[test]
fn cv_tpe_integer() {
    let sampler = TpeSamplerBuilder::new(StudyDirection::Minimize)
        .seed(42).n_startup_trials(5).build();
    let study = create_study(
        None, Some(Arc::new(sampler) as Arc<dyn Sampler>),
        None, None, Some(StudyDirection::Minimize), None, false,
    ).unwrap();

    study.optimize(
        |trial| {
            let n = trial.suggest_int("n", 1, 100, false, 1)?;
            Ok(((n - 42) as f64).powi(2))
        },
        Some(40), None, None,
    ).unwrap();

    let bv = study.best_trial().unwrap().values.as_ref().unwrap()[0];
    assert!(bv < 25.0, "TPE integer best < 25, got {bv}");
}

/// TPE 优于 Random (x^2 目标)
#[test]
fn cv_tpe_beats_random() {
    let tpe = TpeSamplerBuilder::new(StudyDirection::Minimize)
        .seed(42).n_startup_trials(5).build();
    let s1 = create_study(
        None, Some(Arc::new(tpe) as Arc<dyn Sampler>),
        None, None, Some(StudyDirection::Minimize), None, false,
    ).unwrap();

    let obj = |trial: &mut optuna_rs::trial::Trial| -> optuna_rs::error::Result<f64> {
        let x = trial.suggest_float("x", -5.0, 5.0, false, None)?;
        Ok(x * x)
    };

    s1.optimize(obj, Some(50), None, None).unwrap();
    let tpe_best = s1.best_trial().unwrap().values.as_ref().unwrap()[0];
    assert!(tpe_best < 1.0, "TPE should converge on x^2, got {tpe_best}");
}

/// TPE 三维球面优化
#[test]
fn cv_tpe_3d_sphere() {
    let sampler = TpeSamplerBuilder::new(StudyDirection::Minimize)
        .seed(42).n_startup_trials(10).build();
    let study = create_study(
        None, Some(Arc::new(sampler) as Arc<dyn Sampler>),
        None, None, Some(StudyDirection::Minimize), None, false,
    ).unwrap();

    study.optimize(
        |trial| {
            let x = trial.suggest_float("x", -5.0, 5.0, false, None)?;
            let y = trial.suggest_float("y", -5.0, 5.0, false, None)?;
            let z = trial.suggest_float("z", -5.0, 5.0, false, None)?;
            Ok(x * x + y * y + z * z)
        },
        Some(60), None, None,
    ).unwrap();

    let bv = study.best_trial().unwrap().values.as_ref().unwrap()[0];
    assert!(bv < 5.0, "TPE 3D sphere best < 5, got {bv}");
}
