//! TPE ParzenEstimator log_pdf cross-validation tests.
//!
//! Golden values generated by `tests/golden_tpe_split.py` using Python optuna.
//! Tests cover: Float, LogFloat, Integer, Categorical, single-observation edge cases.

use indexmap::IndexMap;
use std::collections::HashMap;

use optuna_rs::distributions::*;
use optuna_rs::samplers::tpe::parzen_estimator::{ParzenEstimator, ParzenEstimatorParameters};

const TOL: f64 = 1e-8;

fn assert_close(actual: f64, expected: f64, tol: f64, msg: &str) {
    if expected.is_infinite() {
        assert!(
            actual.is_infinite() && actual.signum() == expected.signum(),
            "{msg}: expected {expected}, got {actual}"
        );
        return;
    }
    if expected.is_nan() {
        assert!(actual.is_nan(), "{msg}: expected NaN, got {actual}");
        return;
    }
    let diff = (actual - expected).abs();
    let denom = expected.abs().max(1.0);
    assert!(
        diff / denom < tol,
        "{msg}: expected {expected}, got {actual}, rel_diff={:.2e}",
        diff / denom
    );
}

fn assert_vec_close(actual: &[f64], expected: &[f64], tol: f64, msg: &str) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "{msg}: length {}, expected {}",
        actual.len(),
        expected.len()
    );
    for (i, (&a, &e)) in actual.iter().zip(expected.iter()).enumerate() {
        assert_close(a, e, tol, &format!("{msg}[{i}]"));
    }
}

fn default_pe_params() -> ParzenEstimatorParameters {
    ParzenEstimatorParameters::default()
}

// ═══════════════════════════════════════════════════════════════════════════
//  1. Float log_pdf — 3 observations on [0, 10]
//     Python: FloatDistribution(0.0, 10.0), obs=[2,5,8], prior_weight=1.0
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_logpdf_float_3obs_python_golden() {
    let mut ss = IndexMap::new();
    ss.insert(
        "x".to_string(),
        Distribution::FloatDistribution(FloatDistribution::new(0.0, 10.0, false, None).unwrap()),
    );
    let mut obs = HashMap::new();
    obs.insert("x".to_string(), vec![2.0, 5.0, 8.0]);
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    // Python golden: mixture weights = [0.25, 0.25, 0.25, 0.25]
    let expected_weights = [0.25, 0.25, 0.25, 0.25];
    assert_vec_close(pe.weights(), &expected_weights, TOL, "float_3obs_weights");

    // Python golden: mus=[2,5,8,5], sigmas=[3,3,3,10]
    let (mus, sigmas, low, high) = pe.numerical_kernels("x").unwrap();
    assert_vec_close(&mus, &[2.0, 5.0, 8.0, 5.0], TOL, "float_3obs_mus");
    assert_vec_close(&sigmas, &[3.0, 3.0, 3.0, 10.0], TOL, "float_3obs_sigmas");
    assert_close(low, 0.0, TOL, "float_3obs_low");
    assert_close(high, 10.0, TOL, "float_3obs_high");

    // Python golden log_pdf values
    let test_points = vec![0.0, 1.0, 2.0, 3.0, 5.0, 7.0, 8.0, 10.0];
    let expected_logpdf = [
        -2.670406218091419,
        -2.472407766398193,
        -2.323311754094648,
        -2.2219369245113163,
        -2.1453012481753575,
        -2.2219369245113163,
        -2.323311754094648,
        -2.670406218091419,
    ];

    let samples = HashMap::from([("x".to_string(), test_points)]);
    let rust_logpdf = pe.log_pdf(&samples);
    assert_vec_close(&rust_logpdf, &expected_logpdf, TOL, "float_3obs_logpdf");
}

// ═══════════════════════════════════════════════════════════════════════════
//  2. Float log_pdf — symmetry check
//     log_pdf(0) == log_pdf(10) and log_pdf(3) == log_pdf(7) due to
//     symmetric observations [2,5,8] on [0,10]
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_logpdf_float_symmetry() {
    let mut ss = IndexMap::new();
    ss.insert(
        "x".to_string(),
        Distribution::FloatDistribution(FloatDistribution::new(0.0, 10.0, false, None).unwrap()),
    );
    let mut obs = HashMap::new();
    obs.insert("x".to_string(), vec![2.0, 5.0, 8.0]);
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    let samples = HashMap::from([("x".to_string(), vec![0.0, 10.0, 3.0, 7.0])]);
    let logpdf = pe.log_pdf(&samples);
    // Due to symmetric obs: 0↔10, 3↔7
    assert_close(logpdf[0], logpdf[1], TOL, "symmetry 0↔10");
    assert_close(logpdf[2], logpdf[3], TOL, "symmetry 3↔7");
}

// ═══════════════════════════════════════════════════════════════════════════
//  3. Float log_pdf — single observation
//     Python: obs=[5.0], prior_weight=1.0 → weights=[0.5, 0.5]
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_logpdf_float_single_obs_python_golden() {
    let mut ss = IndexMap::new();
    ss.insert(
        "x".to_string(),
        Distribution::FloatDistribution(FloatDistribution::new(0.0, 10.0, false, None).unwrap()),
    );
    let mut obs = HashMap::new();
    obs.insert("x".to_string(), vec![5.0]);
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    // Python golden: weights=[0.5, 0.5]
    assert_vec_close(pe.weights(), &[0.5, 0.5], TOL, "single_obs_weights");

    // Python golden log_pdf at [3,5,7]
    let expected = [-2.2186836715753673, -2.110630488309263, -2.2186836715753673];
    let samples = HashMap::from([("x".to_string(), vec![3.0, 5.0, 7.0])]);
    let rust_logpdf = pe.log_pdf(&samples);
    assert_vec_close(&rust_logpdf, &expected, TOL, "single_obs_logpdf");

    // Symmetry: log_pdf(3) == log_pdf(7) since obs=[5] is symmetric
    assert_close(rust_logpdf[0], rust_logpdf[2], TOL, "single_obs_symmetry");
}

// ═══════════════════════════════════════════════════════════════════════════
//  4. Log float log_pdf — obs on [1e-5, 1.0]
//     Python: FloatDistribution(1e-5, 1.0, log=True), obs=[0.001, 0.01, 0.1]
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_logpdf_log_float_python_golden() {
    let mut ss = IndexMap::new();
    ss.insert(
        "x".to_string(),
        Distribution::FloatDistribution(
            FloatDistribution::new(1e-5, 1.0, true, None).unwrap(),
        ),
    );
    let mut obs = HashMap::new();
    obs.insert("x".to_string(), vec![0.001, 0.01, 0.1]);
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    // Python golden log_pdf values
    let test_points = vec![0.0001, 0.001, 0.01, 0.1, 0.5, 1.0];
    let expected_logpdf = [
        -2.8981215000,
        -2.2947899555,
        -2.0791069410,
        -2.2439458169,
        -2.6240555012,
        -2.8526450681,
    ];

    let samples = HashMap::from([("x".to_string(), test_points)]);
    let rust_logpdf = pe.log_pdf(&samples);
    // Use slightly larger tolerance for log-space computations
    assert_vec_close(&rust_logpdf, &expected_logpdf, 1e-6, "log_float_logpdf");
}

// ═══════════════════════════════════════════════════════════════════════════
//  5. Integer log_pdf — IntDistribution(0, 10)
//     Python: IntDistribution(0, 10), obs=[2,5,8]
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_logpdf_int_python_golden() {
    let mut ss = IndexMap::new();
    ss.insert(
        "x".to_string(),
        Distribution::IntDistribution(IntDistribution::new(0, 10, false, 1).unwrap()),
    );
    let mut obs = HashMap::new();
    obs.insert("x".to_string(), vec![2.0, 5.0, 8.0]);
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    // Python golden log_pdf values
    let test_points = vec![0.0, 2.0, 5.0, 8.0, 10.0];
    let expected_logpdf = [
        -2.7346748227,
        -2.3886499609,
        -2.2088019067,
        -2.3886499609,
        -2.7346748227,
    ];

    let samples = HashMap::from([("x".to_string(), test_points)]);
    let rust_logpdf = pe.log_pdf(&samples);
    assert_vec_close(&rust_logpdf, &expected_logpdf, 1e-6, "int_logpdf");

    // Symmetry: log_pdf(0) == log_pdf(10), log_pdf(2) == log_pdf(8)
    assert_close(rust_logpdf[0], rust_logpdf[4], TOL, "int_symmetry_0_10");
    assert_close(rust_logpdf[1], rust_logpdf[3], TOL, "int_symmetry_2_8");
}

// ═══════════════════════════════════════════════════════════════════════════
//  6. Categorical log_pdf — 4 categories
//     Python: CategoricalDistribution(["a","b","c","d"]), obs=[0,0,1,2]
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_logpdf_categorical_python_golden() {
    let mut ss = IndexMap::new();
    ss.insert(
        "x".to_string(),
        Distribution::CategoricalDistribution(
            CategoricalDistribution::new(vec![
                CategoricalChoice::Str("a".into()),
                CategoricalChoice::Str("b".into()),
                CategoricalChoice::Str("c".into()),
                CategoricalChoice::Str("d".into()),
            ])
            .unwrap(),
        ),
    );
    let mut obs = HashMap::new();
    obs.insert("x".to_string(), vec![0.0, 0.0, 1.0, 2.0]);
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    // Python golden log_pdf values for [0, 1, 2, 3]
    let expected_logpdf = [
        -1.0185695810,
        -1.3862943611,
        -1.3862943611,
        -1.9740810260,
    ];

    let samples = HashMap::from([("x".to_string(), vec![0.0, 1.0, 2.0, 3.0])]);
    let rust_logpdf = pe.log_pdf(&samples);
    assert_vec_close(&rust_logpdf, &expected_logpdf, 1e-6, "cat_logpdf");

    // Category "a" (idx=0) should have highest probability (2 observations)
    assert!(
        rust_logpdf[0] > rust_logpdf[1],
        "cat [a] > [b]: {} > {}",
        rust_logpdf[0],
        rust_logpdf[1]
    );
    // Category "d" (idx=3) should have lowest probability (0 observations)
    assert!(
        rust_logpdf[3] < rust_logpdf[2],
        "cat [d] < [c]: {} < {}",
        rust_logpdf[3],
        rust_logpdf[2]
    );
}

// ═══════════════════════════════════════════════════════════════════════════
//  7. TPE split — single objective (minimize)
//     Python: 8 trials with values [5,1,3,2,4,0.5,6,1.5], gamma=0.25
//     n_below = ceil(0.25 * 8) = 2 → below=[0.5, 1.0], above=[1.5..6.0]
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_tpe_split_single_objective_minimize() {
    // Verify the split logic: sort by value, take n_below best
    let values = vec![5.0, 1.0, 3.0, 2.0, 4.0, 0.5, 6.0, 1.5];
    let n = values.len();
    let n_below = (0.25_f64 * n as f64).ceil() as usize;
    assert_eq!(n_below, 2);

    // Sorted ascending: [0.5, 1.0, 1.5, 2.0, 3.0, 4.0, 5.0, 6.0]
    let mut sorted: Vec<(usize, f64)> = values.iter().copied().enumerate().collect();
    sorted.sort_by(|a, b| a.1.total_cmp(&b.1));

    let below_values: Vec<f64> = sorted[..n_below].iter().map(|&(_, v)| v).collect();
    let above_values: Vec<f64> = sorted[n_below..].iter().map(|&(_, v)| v).collect();

    // Python golden: below = [0.5, 1.0], above = [1.5, 2.0, 3.0, 4.0, 5.0, 6.0]
    assert_eq!(below_values, vec![0.5, 1.0]);
    assert_eq!(above_values, vec![1.5, 2.0, 3.0, 4.0, 5.0, 6.0]);
}

// ═══════════════════════════════════════════════════════════════════════════
//  8. log_pdf monotonicity — peak at observation mass
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_logpdf_float_peak_near_obs() {
    let mut ss = IndexMap::new();
    ss.insert(
        "x".to_string(),
        Distribution::FloatDistribution(FloatDistribution::new(0.0, 10.0, false, None).unwrap()),
    );
    let mut obs = HashMap::new();
    obs.insert("x".to_string(), vec![2.0, 5.0, 8.0]);
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    // log_pdf should be highest near the center of mass (5.0)
    let samples = HashMap::from([("x".to_string(), vec![0.0, 2.0, 5.0, 8.0, 10.0])]);
    let logpdf = pe.log_pdf(&samples);

    // Center (5.0) should have highest log_pdf
    assert!(logpdf[2] > logpdf[0], "center > left edge");
    assert!(logpdf[2] > logpdf[4], "center > right edge");
    // Observations should have higher pdf than edges
    assert!(logpdf[1] > logpdf[0], "obs 2.0 > edge 0.0");
    assert!(logpdf[3] > logpdf[4], "obs 8.0 > edge 10.0");
}

// ═══════════════════════════════════════════════════════════════════════════
//  9. log_pdf — many observations (20)
//     Verify kernel count = n_obs + 1 (prior)
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_logpdf_float_many_obs_kernel_count() {
    let mut ss = IndexMap::new();
    ss.insert(
        "x".to_string(),
        Distribution::FloatDistribution(FloatDistribution::new(0.0, 100.0, false, None).unwrap()),
    );
    let obs_vals: Vec<f64> = (0..20).map(|i| (i as f64) * 5.0 + 2.5).collect();
    let mut obs = HashMap::new();
    obs.insert("x".to_string(), obs_vals);
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    // n_kernels = 20 obs + 1 prior = 21
    assert_eq!(pe.weights().len(), 21, "kernel count = 20 + 1 prior");

    // Weights should sum to 1.0
    let w_sum: f64 = pe.weights().iter().sum();
    assert_close(w_sum, 1.0, TOL, "weights_sum");

    // log_pdf should be finite for all test points
    let test: Vec<f64> = (0..=100).map(|i| i as f64).collect();
    let samples = HashMap::from([("x".to_string(), test)]);
    let logpdf = pe.log_pdf(&samples);
    for (i, &v) in logpdf.iter().enumerate() {
        assert!(v.is_finite(), "log_pdf[{i}] should be finite, got {v}");
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  10. Empty observations — prior only
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_logpdf_float_empty_obs() {
    let mut ss = IndexMap::new();
    ss.insert(
        "x".to_string(),
        Distribution::FloatDistribution(FloatDistribution::new(0.0, 10.0, false, None).unwrap()),
    );
    let obs: HashMap<String, Vec<f64>> = HashMap::new();
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    // Only prior kernel: weights=[1.0]
    assert_eq!(pe.weights().len(), 1, "empty obs → 1 kernel (prior)");
    assert_close(pe.weights()[0], 1.0, TOL, "single prior weight");

    // log_pdf should be symmetric around midpoint
    let samples = HashMap::from([("x".to_string(), vec![0.0, 5.0, 10.0])]);
    let logpdf = pe.log_pdf(&samples);
    // Uniform-like prior → peak at center
    assert!(logpdf[1] > logpdf[0], "center > edge (empty obs)");
    assert_close(logpdf[0], logpdf[2], TOL, "empty obs symmetry");
}

// ═══════════════════════════════════════════════════════════════════════════
//  11. Log float — log_pdf values are consistent with log-space kernel
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_logpdf_log_float_monotonicity() {
    let mut ss = IndexMap::new();
    ss.insert(
        "x".to_string(),
        Distribution::FloatDistribution(
            FloatDistribution::new(1e-5, 1.0, true, None).unwrap(),
        ),
    );
    let mut obs = HashMap::new();
    obs.insert("x".to_string(), vec![0.001, 0.01, 0.1]);
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    // log_pdf at geometric center should be highest
    let samples = HashMap::from([("x".to_string(), vec![1e-5, 0.01, 1.0])]);
    let logpdf = pe.log_pdf(&samples);
    assert!(logpdf[1] > logpdf[0], "geometric center > left edge");
    assert!(logpdf[1] > logpdf[2], "geometric center > right edge");
}

// ═══════════════════════════════════════════════════════════════════════════
//  12. Categorical — uniform prior verification
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_logpdf_categorical_empty_obs() {
    let mut ss = IndexMap::new();
    ss.insert(
        "x".to_string(),
        Distribution::CategoricalDistribution(
            CategoricalDistribution::new(vec![
                CategoricalChoice::Str("a".into()),
                CategoricalChoice::Str("b".into()),
                CategoricalChoice::Str("c".into()),
            ])
            .unwrap(),
        ),
    );
    let obs: HashMap<String, Vec<f64>> = HashMap::new();
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    // With only prior, all categories should have equal probability
    let samples = HashMap::from([("x".to_string(), vec![0.0, 1.0, 2.0])]);
    let logpdf = pe.log_pdf(&samples);
    // All should be equal: ln(1/3)
    let expected_uniform = -(3.0_f64).ln();
    for (i, &v) in logpdf.iter().enumerate() {
        assert_close(v, expected_uniform, TOL, &format!("cat_uniform[{i}]"));
    }
}

// ═══════════════════════════════════════════════════════════════════════════
//  13. Float — log_pdf normalization (exp(log_pdf) integrates ~= 1)
// ═══════════════════════════════════════════════════════════════════════════

#[test]
fn cv_logpdf_float_numerical_integration() {
    let mut ss = IndexMap::new();
    ss.insert(
        "x".to_string(),
        Distribution::FloatDistribution(FloatDistribution::new(0.0, 10.0, false, None).unwrap()),
    );
    let mut obs = HashMap::new();
    obs.insert("x".to_string(), vec![2.0, 5.0, 8.0]);
    let pe = ParzenEstimator::new(&obs, &ss, &default_pe_params(), None, None);

    // Numerical integration: trapezoidal rule with fine grid
    let n_points = 10000;
    let dx = 10.0 / n_points as f64;
    let test_points: Vec<f64> = (0..=n_points).map(|i| i as f64 * dx).collect();
    let samples = HashMap::from([("x".to_string(), test_points)]);
    let logpdf = pe.log_pdf(&samples);

    let mut integral = 0.0;
    for i in 0..logpdf.len() - 1 {
        let pdf_i = logpdf[i].exp();
        let pdf_next = logpdf[i + 1].exp();
        integral += (pdf_i + pdf_next) / 2.0 * dx;
    }

    // Should integrate to ~1.0 (truncated normal mixture)
    assert!(
        (integral - 1.0).abs() < 0.01,
        "pdf integral = {integral}, expected ~1.0"
    );
}
